// Code generated by protoc-gen-go. DO NOT EDIT.
// source: godna.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type Config_Pass_Command int32

const (
	Config_Pass_NONE Config_Pass_Command = 0
)

var Config_Pass_Command_name = map[int32]string{
	0: "NONE",
}

var Config_Pass_Command_value = map[string]int32{
	"NONE": 0,
}

func (x Config_Pass_Command) String() string {
	return proto.EnumName(Config_Pass_Command_name, int32(x))
}

func (Config_Pass_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 0, 0}
}

type Config_Generator_Paths int32

const (
	Config_Generator_Import          Config_Generator_Paths = 0
	Config_Generator_Source_Relative Config_Generator_Paths = 1
)

var Config_Generator_Paths_name = map[int32]string{
	0: "Import",
	1: "Source_Relative",
}

var Config_Generator_Paths_value = map[string]int32{
	"Import":          0,
	"Source_Relative": 1,
}

func (x Config_Generator_Paths) String() string {
	return proto.EnumName(Config_Generator_Paths_name, int32(x))
}

func (Config_Generator_Paths) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 1, 0}
}

// import map
//
type Config_Generator_Go_Plugins int32

const (
	Config_Generator_Go_None Config_Generator_Go_Plugins = 0
	Config_Generator_Go_Grpc Config_Generator_Go_Plugins = 1
)

var Config_Generator_Go_Plugins_name = map[int32]string{
	0: "None",
	1: "Grpc",
}

var Config_Generator_Go_Plugins_value = map[string]int32{
	"None": 0,
	"Grpc": 1,
}

func (x Config_Generator_Go_Plugins) String() string {
	return proto.EnumName(Config_Generator_Go_Plugins_name, int32(x))
}

func (Config_Generator_Go_Plugins) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 1, 1, 0}
}

type Config struct {
	HostOwner            string              `protobuf:"bytes,1,opt,name=host_owner,json=hostOwner,proto3" json:"host_owner,omitempty"`
	RepoName             string              `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	Includes             []string            `protobuf:"bytes,3,rep,name=includes,proto3" json:"includes,omitempty"`
	RelImps              []string            `protobuf:"bytes,4,rep,name=rel_imps,json=relImps,proto3" json:"rel_imps,omitempty"`
	Require              []string            `protobuf:"bytes,5,rep,name=require,proto3" json:"require,omitempty"`
	SrcDir               string              `protobuf:"bytes,6,opt,name=src_dir,json=srcDir,proto3" json:"src_dir,omitempty"`
	OutputDir            string              `protobuf:"bytes,7,opt,name=outputDir,proto3" json:"outputDir,omitempty"`
	Pass                 []*Config_Pass      `protobuf:"bytes,8,rep,name=pass,proto3" json:"pass,omitempty"`
	PluginPath           []string            `protobuf:"bytes,9,rep,name=plugin_path,json=pluginPath,proto3" json:"plugin_path,omitempty"`
	Generator            []*Config_Generator `protobuf:"bytes,10,rep,name=generator,proto3" json:"generator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetHostOwner() string {
	if m != nil {
		return m.HostOwner
	}
	return ""
}

func (m *Config) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *Config) GetIncludes() []string {
	if m != nil {
		return m.Includes
	}
	return nil
}

func (m *Config) GetRelImps() []string {
	if m != nil {
		return m.RelImps
	}
	return nil
}

func (m *Config) GetRequire() []string {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *Config) GetSrcDir() string {
	if m != nil {
		return m.SrcDir
	}
	return ""
}

func (m *Config) GetOutputDir() string {
	if m != nil {
		return m.OutputDir
	}
	return ""
}

func (m *Config) GetPass() []*Config_Pass {
	if m != nil {
		return m.Pass
	}
	return nil
}

func (m *Config) GetPluginPath() []string {
	if m != nil {
		return m.PluginPath
	}
	return nil
}

func (m *Config) GetGenerator() []*Config_Generator {
	if m != nil {
		return m.Generator
	}
	return nil
}

//
type Config_Pass struct {
	Cmd                  []Config_Pass_Command `protobuf:"varint,1,rep,packed,name=cmd,proto3,enum=godna.Config_Pass_Command" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Config_Pass) Reset()         { *m = Config_Pass{} }
func (m *Config_Pass) String() string { return proto.CompactTextString(m) }
func (*Config_Pass) ProtoMessage()    {}
func (*Config_Pass) Descriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 0}
}

func (m *Config_Pass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Pass.Unmarshal(m, b)
}
func (m *Config_Pass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Pass.Marshal(b, m, deterministic)
}
func (m *Config_Pass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Pass.Merge(m, src)
}
func (m *Config_Pass) XXX_Size() int {
	return xxx_messageInfo_Config_Pass.Size(m)
}
func (m *Config_Pass) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Pass.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Pass proto.InternalMessageInfo

func (m *Config_Pass) GetCmd() []Config_Pass_Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type Config_Generator struct {
	Plugin               *Config_Generator_Plugin `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Config_Generator) Reset()         { *m = Config_Generator{} }
func (m *Config_Generator) String() string { return proto.CompactTextString(m) }
func (*Config_Generator) ProtoMessage()    {}
func (*Config_Generator) Descriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 1}
}

func (m *Config_Generator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator.Unmarshal(m, b)
}
func (m *Config_Generator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator.Marshal(b, m, deterministic)
}
func (m *Config_Generator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator.Merge(m, src)
}
func (m *Config_Generator) XXX_Size() int {
	return xxx_messageInfo_Config_Generator.Size(m)
}
func (m *Config_Generator) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator proto.InternalMessageInfo

func (m *Config_Generator) GetPlugin() *Config_Generator_Plugin {
	if m != nil {
		return m.Plugin
	}
	return nil
}

//
type Config_Generator_Plugin struct {
	// Types that are valid to be assigned to Cmd:
	//	*Config_Generator_Plugin_Go
	//	*Config_Generator_Plugin_Micro
	//	*Config_Generator_Plugin_GrpcGateway
	//	*Config_Generator_Plugin_Swagger
	Cmd                  isConfig_Generator_Plugin_Cmd `protobuf_oneof:"cmd"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Config_Generator_Plugin) Reset()         { *m = Config_Generator_Plugin{} }
func (m *Config_Generator_Plugin) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Plugin) ProtoMessage()    {}
func (*Config_Generator_Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 1, 0}
}

func (m *Config_Generator_Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Plugin.Unmarshal(m, b)
}
func (m *Config_Generator_Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Plugin.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Plugin.Merge(m, src)
}
func (m *Config_Generator_Plugin) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Plugin.Size(m)
}
func (m *Config_Generator_Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Plugin proto.InternalMessageInfo

type isConfig_Generator_Plugin_Cmd interface {
	isConfig_Generator_Plugin_Cmd()
}

type Config_Generator_Plugin_Go struct {
	Go *Config_Generator_Go `protobuf:"bytes,1,opt,name=go,proto3,oneof"`
}

type Config_Generator_Plugin_Micro struct {
	Micro *Config_Generator_Micro `protobuf:"bytes,2,opt,name=micro,proto3,oneof"`
}

type Config_Generator_Plugin_GrpcGateway struct {
	GrpcGateway *Config_Generator_Grpc_Gateway `protobuf:"bytes,3,opt,name=grpc_gateway,json=grpcGateway,proto3,oneof"`
}

type Config_Generator_Plugin_Swagger struct {
	Swagger *Config_Generator_Swagger `protobuf:"bytes,4,opt,name=swagger,proto3,oneof"`
}

func (*Config_Generator_Plugin_Go) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_Micro) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_GrpcGateway) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_Swagger) isConfig_Generator_Plugin_Cmd() {}

func (m *Config_Generator_Plugin) GetCmd() isConfig_Generator_Plugin_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *Config_Generator_Plugin) GetGo() *Config_Generator_Go {
	if x, ok := m.GetCmd().(*Config_Generator_Plugin_Go); ok {
		return x.Go
	}
	return nil
}

func (m *Config_Generator_Plugin) GetMicro() *Config_Generator_Micro {
	if x, ok := m.GetCmd().(*Config_Generator_Plugin_Micro); ok {
		return x.Micro
	}
	return nil
}

func (m *Config_Generator_Plugin) GetGrpcGateway() *Config_Generator_Grpc_Gateway {
	if x, ok := m.GetCmd().(*Config_Generator_Plugin_GrpcGateway); ok {
		return x.GrpcGateway
	}
	return nil
}

func (m *Config_Generator_Plugin) GetSwagger() *Config_Generator_Swagger {
	if x, ok := m.GetCmd().(*Config_Generator_Plugin_Swagger); ok {
		return x.Swagger
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Config_Generator_Plugin) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Config_Generator_Plugin_Go)(nil),
		(*Config_Generator_Plugin_Micro)(nil),
		(*Config_Generator_Plugin_GrpcGateway)(nil),
		(*Config_Generator_Plugin_Swagger)(nil),
	}
}

type Config_Generator_Go struct {
	Plugins []Config_Generator_Go_Plugins `protobuf:"varint,1,rep,packed,name=plugins,proto3,enum=godna.Config_Generator_Go_Plugins" json:"plugins,omitempty"`
	Paths   Config_Generator_Paths        `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
	// string import_prefix = 3;
	AnnotateCode         bool     `protobuf:"varint,4,opt,name=annotate_code,json=annotateCode,proto3" json:"annotate_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config_Generator_Go) Reset()         { *m = Config_Generator_Go{} }
func (m *Config_Generator_Go) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Go) ProtoMessage()    {}
func (*Config_Generator_Go) Descriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 1, 1}
}

func (m *Config_Generator_Go) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Go.Unmarshal(m, b)
}
func (m *Config_Generator_Go) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Go.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Go) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Go.Merge(m, src)
}
func (m *Config_Generator_Go) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Go.Size(m)
}
func (m *Config_Generator_Go) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Go.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Go proto.InternalMessageInfo

func (m *Config_Generator_Go) GetPlugins() []Config_Generator_Go_Plugins {
	if m != nil {
		return m.Plugins
	}
	return nil
}

func (m *Config_Generator_Go) GetPaths() Config_Generator_Paths {
	if m != nil {
		return m.Paths
	}
	return Config_Generator_Import
}

func (m *Config_Generator_Go) GetAnnotateCode() bool {
	if m != nil {
		return m.AnnotateCode
	}
	return false
}

type Config_Generator_Micro struct {
	Paths                Config_Generator_Paths `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Config_Generator_Micro) Reset()         { *m = Config_Generator_Micro{} }
func (m *Config_Generator_Micro) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Micro) ProtoMessage()    {}
func (*Config_Generator_Micro) Descriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 1, 2}
}

func (m *Config_Generator_Micro) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Micro.Unmarshal(m, b)
}
func (m *Config_Generator_Micro) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Micro.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Micro) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Micro.Merge(m, src)
}
func (m *Config_Generator_Micro) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Micro.Size(m)
}
func (m *Config_Generator_Micro) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Micro.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Micro proto.InternalMessageInfo

func (m *Config_Generator_Micro) GetPaths() Config_Generator_Paths {
	if m != nil {
		return m.Paths
	}
	return Config_Generator_Import
}

type Config_Generator_Grpc_Gateway struct {
	Paths                Config_Generator_Paths `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
	RegisterFuncSuffix   string                 `protobuf:"bytes,3,opt,name=register_func_suffix,json=registerFuncSuffix,proto3" json:"register_func_suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Config_Generator_Grpc_Gateway) Reset()         { *m = Config_Generator_Grpc_Gateway{} }
func (m *Config_Generator_Grpc_Gateway) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Grpc_Gateway) ProtoMessage()    {}
func (*Config_Generator_Grpc_Gateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 1, 3}
}

func (m *Config_Generator_Grpc_Gateway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Grpc_Gateway.Unmarshal(m, b)
}
func (m *Config_Generator_Grpc_Gateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Grpc_Gateway.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Grpc_Gateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Grpc_Gateway.Merge(m, src)
}
func (m *Config_Generator_Grpc_Gateway) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Grpc_Gateway.Size(m)
}
func (m *Config_Generator_Grpc_Gateway) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Grpc_Gateway.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Grpc_Gateway proto.InternalMessageInfo

func (m *Config_Generator_Grpc_Gateway) GetPaths() Config_Generator_Paths {
	if m != nil {
		return m.Paths
	}
	return Config_Generator_Import
}

func (m *Config_Generator_Grpc_Gateway) GetRegisterFuncSuffix() string {
	if m != nil {
		return m.RegisterFuncSuffix
	}
	return ""
}

type Config_Generator_Swagger struct {
	Logtostderr          bool     `protobuf:"varint,1,opt,name=logtostderr,proto3" json:"logtostderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config_Generator_Swagger) Reset()         { *m = Config_Generator_Swagger{} }
func (m *Config_Generator_Swagger) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Swagger) ProtoMessage()    {}
func (*Config_Generator_Swagger) Descriptor() ([]byte, []int) {
	return fileDescriptor_3171b004c42f86ef, []int{0, 1, 4}
}

func (m *Config_Generator_Swagger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Swagger.Unmarshal(m, b)
}
func (m *Config_Generator_Swagger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Swagger.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Swagger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Swagger.Merge(m, src)
}
func (m *Config_Generator_Swagger) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Swagger.Size(m)
}
func (m *Config_Generator_Swagger) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Swagger.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Swagger proto.InternalMessageInfo

func (m *Config_Generator_Swagger) GetLogtostderr() bool {
	if m != nil {
		return m.Logtostderr
	}
	return false
}

var E_Cfg = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*Config)(nil),
	Field:         49999,
	Name:          "godna.cfg",
	Tag:           "bytes,49999,opt,name=cfg",
	Filename:      "godna.proto",
}

var E_Help = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         49999,
	Name:          "godna.help",
	Tag:           "bytes,49999,opt,name=help",
	Filename:      "godna.proto",
}

func init() {
	proto.RegisterEnum("godna.Config_Pass_Command", Config_Pass_Command_name, Config_Pass_Command_value)
	proto.RegisterEnum("godna.Config_Generator_Paths", Config_Generator_Paths_name, Config_Generator_Paths_value)
	proto.RegisterEnum("godna.Config_Generator_Go_Plugins", Config_Generator_Go_Plugins_name, Config_Generator_Go_Plugins_value)
	proto.RegisterType((*Config)(nil), "godna.Config")
	proto.RegisterType((*Config_Pass)(nil), "godna.Config.Pass")
	proto.RegisterType((*Config_Generator)(nil), "godna.Config.Generator")
	proto.RegisterType((*Config_Generator_Plugin)(nil), "godna.Config.Generator.Plugin")
	proto.RegisterType((*Config_Generator_Go)(nil), "godna.Config.Generator.Go")
	proto.RegisterType((*Config_Generator_Micro)(nil), "godna.Config.Generator.Micro")
	proto.RegisterType((*Config_Generator_Grpc_Gateway)(nil), "godna.Config.Generator.Grpc_Gateway")
	proto.RegisterType((*Config_Generator_Swagger)(nil), "godna.Config.Generator.Swagger")
	proto.RegisterExtension(E_Cfg)
	proto.RegisterExtension(E_Help)
}

func init() { proto.RegisterFile("godna.proto", fileDescriptor_3171b004c42f86ef) }

var fileDescriptor_3171b004c42f86ef = []byte{
	// 1259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdf, 0x6e, 0x1b, 0xc5,
	0x17, 0x8e, 0xf3, 0xc7, 0x8e, 0x27, 0x6d, 0x7f, 0xd1, 0xf4, 0x87, 0x58, 0x2c, 0x0a, 0x47, 0x06,
	0x29, 0x29, 0xd8, 0x9b, 0x92, 0x08, 0x2a, 0x85, 0x46, 0xa5, 0x69, 0x9b, 0xc4, 0x17, 0xf9, 0xa3,
	0x4d, 0x7b, 0x43, 0x64, 0x99, 0xc9, 0xee, 0xf1, 0x7a, 0xe8, 0xee, 0xcc, 0x76, 0x66, 0xd6, 0xad,
	0x25, 0x2e, 0xb8, 0xe2, 0x8a, 0xa7, 0xe0, 0x19, 0x7c, 0x83, 0x90, 0x78, 0x04, 0xb8, 0xe0, 0x5d,
	0xb8, 0x30, 0xbd, 0x40, 0x33, 0xbb, 0x4e, 0x52, 0x8a, 0x25, 0xd4, 0x9b, 0x64, 0xf6, 0xcc, 0x77,
	0xbe, 0x33, 0xe7, 0x3b, 0xdf, 0xac, 0x97, 0xac, 0xc4, 0x32, 0x12, 0xcc, 0xcf, 0x94, 0x34, 0x92,
	0x2e, 0xb9, 0x87, 0x06, 0xc4, 0x52, 0xc6, 0x09, 0x6e, 0xb8, 0xe0, 0x79, 0xde, 0xdf, 0x88, 0x50,
	0x87, 0x8a, 0x67, 0x46, 0xaa, 0x02, 0xd8, 0xfc, 0x6b, 0x95, 0x54, 0x1f, 0x4a, 0xd1, 0xe7, 0x31,
	0x4d, 0x08, 0x19, 0x48, 0x6d, 0x7a, 0xf2, 0x85, 0x40, 0xe5, 0x55, 0xa0, 0xb2, 0x5e, 0xdf, 0x3d,
	0x9c, 0x8c, 0xbd, 0x8e, 0x8d, 0x02, 0x13, 0x11, 0xb8, 0x1d, 0x90, 0x7d, 0x30, 0x03, 0x04, 0x85,
	0x99, 0x9c, 0xae, 0x63, 0x14, 0xa8, 0x98, 0xc1, 0x08, 0x42, 0x19, 0x21, 0x60, 0xec, 0x43, 0xcc,
	0xcd, 0x20, 0x3f, 0xf7, 0x43, 0x99, 0x6e, 0xa4, 0x3c, 0x54, 0x52, 0xcb, 0xbe, 0x09, 0xea, 0x96,
	0xea, 0xd8, 0xb2, 0xd0, 0x43, 0x52, 0xb7, 0x0c, 0x3d, 0xc1, 0x52, 0xf4, 0xe6, 0x5d, 0xb1, 0x3b,
	0x93, 0xb1, 0xd7, 0x72, 0xb4, 0x36, 0x38, 0x93, 0x1b, 0x62, 0xd9, 0x1e, 0x6a, 0xfb, 0x10, 0x2c,
	0x5b, 0xf4, 0x11, 0x4b, 0x91, 0x1e, 0x93, 0x65, 0x2e, 0xc2, 0x24, 0x8f, 0x50, 0x7b, 0x0b, 0xb0,
	0xb0, 0x5e, 0xdf, 0xdd, 0x9a, 0x8c, 0xbd, 0xa2, 0xf1, 0x10, 0x32, 0x66, 0x06, 0xd0, 0xee, 0xd8,
	0xe4, 0x33, 0x58, 0xf3, 0xfd, 0xcb, 0x23, 0xb5, 0x23, 0xc1, 0x36, 0x86, 0x28, 0x22, 0xa9, 0xd6,
	0xa0, 0x1b, 0x5c, 0x90, 0xd0, 0x88, 0x2c, 0x2b, 0x4c, 0x7a, 0x3c, 0xcd, 0xb4, 0xb7, 0xe8, 0x08,
	0x3b, 0x93, 0xb1, 0xf7, 0x38, 0x53, 0xd8, 0xe7, 0x2f, 0xed, 0xd9, 0x62, 0xe9, 0xa7, 0x32, 0x82,
	0x44, 0x86, 0x2c, 0xb1, 0x62, 0x24, 0x2c, 0xc4, 0x14, 0x85, 0xd1, 0x7e, 0x59, 0x46, 0xa3, 0x1a,
	0xf2, 0x10, 0x75, 0x7b, 0x0d, 0xba, 0xd0, 0x06, 0x23, 0x23, 0x09, 0x0a, 0x53, 0x39, 0xc4, 0xa0,
	0xa6, 0x30, 0xe9, 0xa4, 0x99, 0xa6, 0xdf, 0x90, 0x9a, 0xc2, 0xe7, 0x39, 0x57, 0xe8, 0x2d, 0xb9,
	0x22, 0x7b, 0x93, 0xb1, 0xb7, 0x9b, 0x70, 0x6d, 0x8a, 0x12, 0x60, 0x4b, 0x60, 0xc4, 0x0d, 0xb4,
	0x4b, 0xdc, 0x4e, 0xc9, 0x7e, 0x45, 0xdf, 0x58, 0x26, 0x4c, 0xc4, 0xcf, 0x37, 0x9e, 0x7f, 0x35,
	0xfc, 0xcc, 0xbf, 0xe3, 0xdf, 0xb5, 0x8d, 0x4c, 0x69, 0xe9, 0x33, 0x52, 0xd3, 0x2a, 0xec, 0x45,
	0x5c, 0x79, 0x55, 0xa7, 0x72, 0x30, 0x19, 0x7b, 0x47, 0x5a, 0xe6, 0x2a, 0x44, 0x88, 0xb8, 0xc2,
	0xd0, 0x48, 0x35, 0xb2, 0xa4, 0x6f, 0xc8, 0xa2, 0x8d, 0x54, 0xce, 0x3b, 0xdf, 0x62, 0x68, 0xa0,
	0x0d, 0x42, 0x1a, 0xb4, 0x7f, 0xa0, 0x14, 0x29, 0x02, 0xa6, 0x81, 0x41, 0xbb, 0x13, 0x54, 0xb5,
	0x0a, 0x1f, 0x71, 0x45, 0xef, 0x92, 0xba, 0xcc, 0x4d, 0x96, 0x9b, 0x47, 0x5c, 0x79, 0x35, 0x57,
	0xee, 0xbd, 0xc9, 0xd8, 0x7b, 0xa7, 0x08, 0xfe, 0xa3, 0x5c, 0x70, 0x89, 0xa5, 0xaf, 0x2a, 0x64,
	0x31, 0x63, 0x5a, 0x7b, 0xcb, 0xb0, 0xb0, 0xbe, 0xb2, 0x49, 0xfd, 0xc2, 0xcc, 0x85, 0x33, 0xfd,
	0x13, 0xa6, 0xf5, 0xee, 0x1f, 0x95, 0xc9, 0xd8, 0xfb, 0xad, 0x12, 0xca, 0x34, 0x95, 0x02, 0x34,
	0x66, 0xac, 0x70, 0xc5, 0x54, 0x2c, 0xbb, 0xc1, 0x44, 0xa4, 0xc1, 0x48, 0x50, 0xb9, 0xf0, 0xe1,
	0x44, 0x6a, 0xcd, 0xcf, 0x13, 0xbc, 0xdc, 0x61, 0x0a, 0xa1, 0x70, 0x44, 0x2b, 0x95, 0x11, 0x17,
	0xdc, 0xd8, 0xff, 0xa5, 0x52, 0xc5, 0xd2, 0x8d, 0xd1, 0x2e, 0x0d, 0x8f, 0x46, 0xad, 0x98, 0x1b,
	0xc3, 0x62, 0x58, 0x8f, 0xb0, 0xcf, 0xf2, 0xc4, 0xc0, 0x59, 0xf3, 0xbf, 0xa4, 0x37, 0x5b, 0xd0,
	0x2c, 0x19, 0xec, 0xb2, 0x20, 0x29, 0x83, 0x25, 0xda, 0xb9, 0xa6, 0xd9, 0xbd, 0x1d, 0xb8, 0xae,
	0xe9, 0x4f, 0x15, 0xb2, 0x92, 0x25, 0x79, 0xcc, 0x45, 0xcf, 0x5a, 0xd5, 0xab, 0x3b, 0x2f, 0x7c,
	0x6f, 0x3b, 0xfe, 0xce, 0xda, 0xdb, 0xdd, 0x3e, 0x67, 0x62, 0xd9, 0x07, 0x06, 0x05, 0x34, 0xb6,
	0x2a, 0x16, 0xe7, 0x69, 0xc7, 0x28, 0xda, 0x47, 0x0f, 0x0e, 0x1f, 0xef, 0x58, 0xd0, 0x86, 0x91,
	0x1b, 0xe9, 0xe8, 0x9c, 0x0b, 0xa6, 0x46, 0x3e, 0x1c, 0xe6, 0xe1, 0x00, 0x58, 0xa2, 0x25, 0xe8,
	0x0c, 0x43, 0xde, 0x1f, 0x41, 0xbb, 0x5d, 0xde, 0x29, 0xa9, 0x5a, 0x10, 0x49, 0xd4, 0xc5, 0x50,
	0xd3, 0x2c, 0x19, 0x01, 0x37, 0x00, 0x5c, 0x43, 0xa6, 0x50, 0xa3, 0x30, 0x01, 0x29, 0x4a, 0x9d,
	0x30, 0x33, 0xa0, 0x7f, 0x56, 0x48, 0xfd, 0x22, 0xd1, 0x23, 0x6e, 0x50, 0xef, 0xbe, 0x3e, 0xa8,
	0xfd, 0xe9, 0xf6, 0xee, 0xaf, 0xf6, 0xec, 0x3f, 0x57, 0xae, 0x1c, 0x5e, 0xb1, 0xd4, 0xba, 0xe5,
	0x82, 0xc1, 0x87, 0x3d, 0xa9, 0x52, 0x77, 0xd5, 0xcf, 0x76, 0x9e, 0xe1, 0x68, 0x67, 0xc8, 0x92,
	0x1c, 0xcf, 0x5a, 0x67, 0x17, 0xeb, 0x6e, 0xf7, 0x93, 0xee, 0xfd, 0xb3, 0x6d, 0x99, 0x1b, 0x6b,
	0xdf, 0xee, 0x7d, 0x1f, 0x4e, 0x11, 0xc1, 0xcd, 0xc2, 0x40, 0x5f, 0x2a, 0x60, 0x02, 0xf0, 0x25,
	0x4b, 0xb3, 0x04, 0x7d, 0x78, 0x92, 0x2b, 0xa1, 0x81, 0x0b, 0x23, 0x61, 0xad, 0xed, 0xb4, 0xe8,
	0xc9, 0xdc, 0xec, 0x9c, 0x3c, 0x08, 0x0e, 0x1f, 0x9c, 0x6e, 0x1f, 0x3f, 0x7d, 0x72, 0xf2, 0xf4,
	0x49, 0xef, 0x51, 0x27, 0x58, 0xf3, 0x2f, 0xc7, 0xb9, 0x16, 0x4b, 0x27, 0x98, 0xde, 0x29, 0xee,
	0x43, 0x4f, 0x61, 0xc2, 0x0c, 0x1f, 0xe2, 0xda, 0xed, 0xe0, 0xb2, 0xd5, 0x46, 0x87, 0x2c, 0x5a,
	0x07, 0xd2, 0x16, 0x59, 0x08, 0xd3, 0xc8, 0xab, 0xc0, 0xc2, 0xfa, 0x8d, 0xcd, 0xc6, 0x9b, 0x16,
	0xf5, 0x1f, 0x16, 0x46, 0x0b, 0x2c, 0xac, 0x79, 0x93, 0xd4, 0xca, 0x67, 0xba, 0x4c, 0x16, 0x8f,
	0x8e, 0x8f, 0x1e, 0xaf, 0xce, 0x35, 0x7e, 0xac, 0x92, 0xfa, 0x85, 0x48, 0xf4, 0x0b, 0x52, 0x2d,
	0xf4, 0x75, 0x6f, 0xdb, 0x95, 0xcd, 0x0f, 0x66, 0xa8, 0xe9, 0x9f, 0x38, 0x54, 0x50, 0xa2, 0x1b,
	0xaf, 0x2a, 0xa4, 0x5a, 0x84, 0x68, 0x8b, 0xcc, 0xc7, 0xb2, 0x4c, 0x6f, 0xcc, 0x4a, 0xdf, 0x97,
	0x07, 0x73, 0xc1, 0x7c, 0x2c, 0xe9, 0xe7, 0x64, 0xc9, 0x5d, 0x71, 0xf7, 0xc2, 0x5d, 0xd9, 0xbc,
	0x35, 0x2b, 0xe1, 0xd0, 0x82, 0x0e, 0xe6, 0x82, 0x02, 0x4d, 0x3b, 0xe4, 0x5a, 0xac, 0xb2, 0xb0,
	0x17, 0x33, 0x83, 0x2f, 0xd8, 0xc8, 0x5b, 0x70, 0xd9, 0x1f, 0xcf, 0x2c, 0x67, 0xb1, 0xfb, 0x05,
	0xf6, 0x60, 0x2e, 0x58, 0xb1, 0xb9, 0xe5, 0x23, 0xfd, 0x92, 0xd4, 0xf4, 0x0b, 0x16, 0xc7, 0xa8,
	0xbc, 0x45, 0xc7, 0xf2, 0xe1, 0x2c, 0x96, 0xd3, 0x02, 0x76, 0x30, 0x17, 0x4c, 0x33, 0x76, 0x97,
	0xdc, 0x00, 0x1a, 0xbf, 0x54, 0xc8, 0xfc, 0xbe, 0xa4, 0xf7, 0x48, 0xad, 0xd0, 0x43, 0x97, 0x23,
	0x69, 0xce, 0xee, 0xbf, 0x54, 0x50, 0x07, 0xd3, 0x14, 0xba, 0x45, 0x96, 0xdc, 0xe8, 0x9d, 0x14,
	0x37, 0x66, 0x4b, 0x61, 0xad, 0xaf, 0x83, 0x02, 0x4b, 0x3f, 0x22, 0xd7, 0x99, 0x10, 0xd2, 0x30,
	0x83, 0x3d, 0xfb, 0x03, 0xe4, 0x7a, 0x58, 0x0e, 0xae, 0x4d, 0x83, 0x0f, 0x65, 0x84, 0xcd, 0x5b,
	0xa4, 0x56, 0x56, 0x73, 0x83, 0x97, 0x02, 0x57, 0xe7, 0xec, 0xca, 0xca, 0xb2, 0x5a, 0x69, 0xdc,
	0x23, 0x4b, 0x4e, 0xde, 0xb7, 0x3a, 0x41, 0x23, 0x27, 0xd7, 0xae, 0xca, 0xfb, 0x76, 0x6d, 0xdc,
	0x21, 0xff, 0x57, 0x18, 0x73, 0x6d, 0x50, 0xf5, 0xfa, 0xb9, 0x08, 0x7b, 0x3a, 0xef, 0xf7, 0xf9,
	0x4b, 0x37, 0xd7, 0x7a, 0x40, 0xa7, 0x7b, 0x7b, 0xb9, 0x08, 0x4f, 0xdd, 0x4e, 0xe3, 0x53, 0x52,
	0x2b, 0xe7, 0x41, 0x81, 0xac, 0x24, 0x32, 0x36, 0x52, 0x9b, 0x08, 0x55, 0xf1, 0x9d, 0xb0, 0x1c,
	0x5c, 0x0d, 0x35, 0xd7, 0xc9, 0x92, 0x2b, 0x47, 0x09, 0xa9, 0x76, 0xd2, 0x4c, 0x2a, 0xb3, 0x3a,
	0x47, 0x6f, 0x92, 0xff, 0x9d, 0x16, 0x97, 0x2c, 0x28, 0x2f, 0xd9, 0x6a, 0x65, 0xfb, 0x3e, 0x59,
	0x08, 0xfb, 0x31, 0x7d, 0xdf, 0x2f, 0xbe, 0x53, 0xfc, 0xe9, 0x77, 0x8a, 0xbf, 0xc7, 0x13, 0x3c,
	0xce, 0x0c, 0x97, 0x42, 0x7b, 0xbf, 0xff, 0x50, 0xf8, 0xed, 0xfa, 0x6b, 0xbd, 0x05, 0x36, 0x73,
	0x7b, 0x8b, 0x2c, 0x0e, 0x30, 0xc9, 0xe8, 0xad, 0x7f, 0x61, 0xc0, 0x24, 0x7a, 0x9d, 0xa2, 0x1e,
	0x38, 0xf0, 0x6e, 0xf5, 0xeb, 0xc5, 0x94, 0x71, 0x71, 0x5e, 0x75, 0xe0, 0xad, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xba, 0x4b, 0xa9, 0xf4, 0x3a, 0x09, 0x00, 0x00,
}
