// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dna/config/config.v1.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/wxio/godna/pb/extensions/store"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type Config_PluginOutDir_OutType int32

const (
	Config_PluginOutDir_NOTHING_SPECIAL Config_PluginOutDir_OutType = 0
	Config_PluginOutDir_GO_MODS         Config_PluginOutDir_OutType = 1
)

var Config_PluginOutDir_OutType_name = map[int32]string{
	0: "NOTHING_SPECIAL",
	1: "GO_MODS",
}

var Config_PluginOutDir_OutType_value = map[string]int32{
	"NOTHING_SPECIAL": 0,
	"GO_MODS":         1,
}

func (x Config_PluginOutDir_OutType) String() string {
	return proto.EnumName(Config_PluginOutDir_OutType_name, int32(x))
}

func (Config_PluginOutDir_OutType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 0, 0}
}

//
type Config_Pass_Command int32

const (
	Config_Pass_NONE            Config_Pass_Command = 0
	Config_Pass_PROTOC          Config_Pass_Command = 1
	Config_Pass_MOD_INIT        Config_Pass_Command = 2
	Config_Pass_MOD_REQUIRE     Config_Pass_Command = 3
	Config_Pass_MOD_REPLACE     Config_Pass_Command = 4
	Config_Pass_MOD_TIDY        Config_Pass_Command = 5
	Config_Pass_GIT_ADD_NEXTTAG Config_Pass_Command = 6
	Config_Pass_GIT_TAG         Config_Pass_Command = 7
)

var Config_Pass_Command_name = map[int32]string{
	0: "NONE",
	1: "PROTOC",
	2: "MOD_INIT",
	3: "MOD_REQUIRE",
	4: "MOD_REPLACE",
	5: "MOD_TIDY",
	6: "GIT_ADD_NEXTTAG",
	7: "GIT_TAG",
}

var Config_Pass_Command_value = map[string]int32{
	"NONE":            0,
	"PROTOC":          1,
	"MOD_INIT":        2,
	"MOD_REQUIRE":     3,
	"MOD_REPLACE":     4,
	"MOD_TIDY":        5,
	"GIT_ADD_NEXTTAG": 6,
	"GIT_TAG":         7,
}

func (x Config_Pass_Command) String() string {
	return proto.EnumName(Config_Pass_Command_name, int32(x))
}

func (Config_Pass_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 1, 0}
}

type Config_Generator_Paths int32

const (
	Config_Generator_Import          Config_Generator_Paths = 0
	Config_Generator_Source_Relative Config_Generator_Paths = 1
)

var Config_Generator_Paths_name = map[int32]string{
	0: "Import",
	1: "Source_Relative",
}

var Config_Generator_Paths_value = map[string]int32{
	"Import":          0,
	"Source_Relative": 1,
}

func (x Config_Generator_Paths) String() string {
	return proto.EnumName(Config_Generator_Paths_name, int32(x))
}

func (Config_Generator_Paths) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 2, 0}
}

// map<string,string> importMap = 5;
//
type Config_Generator_Go_Plugins int32

const (
	Config_Generator_Go_None Config_Generator_Go_Plugins = 0
	Config_Generator_Go_Grpc Config_Generator_Go_Plugins = 1
)

var Config_Generator_Go_Plugins_name = map[int32]string{
	0: "None",
	1: "Grpc",
}

var Config_Generator_Go_Plugins_value = map[string]int32{
	"None": 0,
	"Grpc": 1,
}

func (x Config_Generator_Go_Plugins) String() string {
	return proto.EnumName(Config_Generator_Go_Plugins_name, int32(x))
}

func (Config_Generator_Go_Plugins) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 2, 1, 0}
}

type Config struct {
	HostOwner string `protobuf:"bytes,1,opt,name=host_owner,json=hostOwner,proto3" json:"host_owner,omitempty"`
	//TODO protobuf validators eg [(validator.maditory) = true]
	RepoName string   `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	Includes []string `protobuf:"bytes,3,rep,name=includes,proto3" json:"includes,omitempty"`
	RelImps  []string `protobuf:"bytes,4,rep,name=rel_imps,json=relImps,proto3" json:"rel_imps,omitempty"`
	Require  []string `protobuf:"bytes,5,rep,name=require,proto3" json:"require,omitempty"`
	SrcDir   string   `protobuf:"bytes,6,opt,name=src_dir,json=srcDir,proto3" json:"src_dir,omitempty"`
	// string   output_root              = 7
	// [(wxio.extensions.store.help) = "output root directory eg ."];
	Pass                 []*Config_Pass         `protobuf:"bytes,8,rep,name=pass,proto3" json:"pass,omitempty"`
	PluginPath           []string               `protobuf:"bytes,9,rep,name=plugin_path,json=pluginPath,proto3" json:"plugin_path,omitempty"`
	PluginOutputDir      []*Config_PluginOutDir `protobuf:"bytes,10,rep,name=plugin_output_dir,json=pluginOutputDir,proto3" json:"plugin_output_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetHostOwner() string {
	if m != nil {
		return m.HostOwner
	}
	return ""
}

func (m *Config) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *Config) GetIncludes() []string {
	if m != nil {
		return m.Includes
	}
	return nil
}

func (m *Config) GetRelImps() []string {
	if m != nil {
		return m.RelImps
	}
	return nil
}

func (m *Config) GetRequire() []string {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *Config) GetSrcDir() string {
	if m != nil {
		return m.SrcDir
	}
	return ""
}

func (m *Config) GetPass() []*Config_Pass {
	if m != nil {
		return m.Pass
	}
	return nil
}

func (m *Config) GetPluginPath() []string {
	if m != nil {
		return m.PluginPath
	}
	return nil
}

func (m *Config) GetPluginOutputDir() []*Config_PluginOutDir {
	if m != nil {
		return m.PluginOutputDir
	}
	return nil
}

//
type Config_PluginOutDir struct {
	Path                 string                      `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	OutType              Config_PluginOutDir_OutType `protobuf:"varint,2,opt,name=out_type,json=outType,proto3,enum=godna.Config_PluginOutDir_OutType" json:"out_type,omitempty"`
	Generator            []*Config_Generator         `protobuf:"bytes,3,rep,name=generator,proto3" json:"generator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Config_PluginOutDir) Reset()         { *m = Config_PluginOutDir{} }
func (m *Config_PluginOutDir) String() string { return proto.CompactTextString(m) }
func (*Config_PluginOutDir) ProtoMessage()    {}
func (*Config_PluginOutDir) Descriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 0}
}

func (m *Config_PluginOutDir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_PluginOutDir.Unmarshal(m, b)
}
func (m *Config_PluginOutDir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_PluginOutDir.Marshal(b, m, deterministic)
}
func (m *Config_PluginOutDir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_PluginOutDir.Merge(m, src)
}
func (m *Config_PluginOutDir) XXX_Size() int {
	return xxx_messageInfo_Config_PluginOutDir.Size(m)
}
func (m *Config_PluginOutDir) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_PluginOutDir.DiscardUnknown(m)
}

var xxx_messageInfo_Config_PluginOutDir proto.InternalMessageInfo

func (m *Config_PluginOutDir) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Config_PluginOutDir) GetOutType() Config_PluginOutDir_OutType {
	if m != nil {
		return m.OutType
	}
	return Config_PluginOutDir_NOTHING_SPECIAL
}

func (m *Config_PluginOutDir) GetGenerator() []*Config_Generator {
	if m != nil {
		return m.Generator
	}
	return nil
}

type Config_Pass struct {
	Cmd                  []Config_Pass_Command `protobuf:"varint,1,rep,packed,name=cmd,proto3,enum=godna.Config_Pass_Command" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Config_Pass) Reset()         { *m = Config_Pass{} }
func (m *Config_Pass) String() string { return proto.CompactTextString(m) }
func (*Config_Pass) ProtoMessage()    {}
func (*Config_Pass) Descriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 1}
}

func (m *Config_Pass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Pass.Unmarshal(m, b)
}
func (m *Config_Pass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Pass.Marshal(b, m, deterministic)
}
func (m *Config_Pass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Pass.Merge(m, src)
}
func (m *Config_Pass) XXX_Size() int {
	return xxx_messageInfo_Config_Pass.Size(m)
}
func (m *Config_Pass) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Pass.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Pass proto.InternalMessageInfo

func (m *Config_Pass) GetCmd() []Config_Pass_Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

type Config_Generator struct {
	Plugin               *Config_Generator_Plugin `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Config_Generator) Reset()         { *m = Config_Generator{} }
func (m *Config_Generator) String() string { return proto.CompactTextString(m) }
func (*Config_Generator) ProtoMessage()    {}
func (*Config_Generator) Descriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 2}
}

func (m *Config_Generator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator.Unmarshal(m, b)
}
func (m *Config_Generator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator.Marshal(b, m, deterministic)
}
func (m *Config_Generator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator.Merge(m, src)
}
func (m *Config_Generator) XXX_Size() int {
	return xxx_messageInfo_Config_Generator.Size(m)
}
func (m *Config_Generator) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator proto.InternalMessageInfo

func (m *Config_Generator) GetPlugin() *Config_Generator_Plugin {
	if m != nil {
		return m.Plugin
	}
	return nil
}

//
type Config_Generator_Plugin struct {
	// Types that are valid to be assigned to Cmd:
	//	*Config_Generator_Plugin_Go
	//	*Config_Generator_Plugin_Micro
	//	*Config_Generator_Plugin_GrpcGateway
	//	*Config_Generator_Plugin_Swagger
	Cmd                  isConfig_Generator_Plugin_Cmd `protobuf_oneof:"cmd"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Config_Generator_Plugin) Reset()         { *m = Config_Generator_Plugin{} }
func (m *Config_Generator_Plugin) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Plugin) ProtoMessage()    {}
func (*Config_Generator_Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 2, 0}
}

func (m *Config_Generator_Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Plugin.Unmarshal(m, b)
}
func (m *Config_Generator_Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Plugin.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Plugin.Merge(m, src)
}
func (m *Config_Generator_Plugin) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Plugin.Size(m)
}
func (m *Config_Generator_Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Plugin proto.InternalMessageInfo

type isConfig_Generator_Plugin_Cmd interface {
	isConfig_Generator_Plugin_Cmd()
}

type Config_Generator_Plugin_Go struct {
	Go *Config_Generator_Go `protobuf:"bytes,1,opt,name=go,proto3,oneof"`
}

type Config_Generator_Plugin_Micro struct {
	Micro *Config_Generator_Micro `protobuf:"bytes,2,opt,name=micro,proto3,oneof"`
}

type Config_Generator_Plugin_GrpcGateway struct {
	GrpcGateway *Config_Generator_Grpc_Gateway `protobuf:"bytes,3,opt,name=grpc_gateway,json=grpcGateway,proto3,oneof"`
}

type Config_Generator_Plugin_Swagger struct {
	Swagger *Config_Generator_Swagger `protobuf:"bytes,4,opt,name=swagger,proto3,oneof"`
}

func (*Config_Generator_Plugin_Go) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_Micro) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_GrpcGateway) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_Swagger) isConfig_Generator_Plugin_Cmd() {}

func (m *Config_Generator_Plugin) GetCmd() isConfig_Generator_Plugin_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *Config_Generator_Plugin) GetGo() *Config_Generator_Go {
	if x, ok := m.GetCmd().(*Config_Generator_Plugin_Go); ok {
		return x.Go
	}
	return nil
}

func (m *Config_Generator_Plugin) GetMicro() *Config_Generator_Micro {
	if x, ok := m.GetCmd().(*Config_Generator_Plugin_Micro); ok {
		return x.Micro
	}
	return nil
}

func (m *Config_Generator_Plugin) GetGrpcGateway() *Config_Generator_Grpc_Gateway {
	if x, ok := m.GetCmd().(*Config_Generator_Plugin_GrpcGateway); ok {
		return x.GrpcGateway
	}
	return nil
}

func (m *Config_Generator_Plugin) GetSwagger() *Config_Generator_Swagger {
	if x, ok := m.GetCmd().(*Config_Generator_Plugin_Swagger); ok {
		return x.Swagger
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Config_Generator_Plugin) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Config_Generator_Plugin_Go)(nil),
		(*Config_Generator_Plugin_Micro)(nil),
		(*Config_Generator_Plugin_GrpcGateway)(nil),
		(*Config_Generator_Plugin_Swagger)(nil),
	}
}

type Config_Generator_Go struct {
	Plugins []Config_Generator_Go_Plugins `protobuf:"varint,1,rep,packed,name=plugins,proto3,enum=godna.Config_Generator_Go_Plugins" json:"plugins,omitempty"`
	Paths   Config_Generator_Paths        `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
	// string import_prefix = 3;
	AnnotateCode         bool     `protobuf:"varint,4,opt,name=annotate_code,json=annotateCode,proto3" json:"annotate_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config_Generator_Go) Reset()         { *m = Config_Generator_Go{} }
func (m *Config_Generator_Go) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Go) ProtoMessage()    {}
func (*Config_Generator_Go) Descriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 2, 1}
}

func (m *Config_Generator_Go) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Go.Unmarshal(m, b)
}
func (m *Config_Generator_Go) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Go.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Go) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Go.Merge(m, src)
}
func (m *Config_Generator_Go) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Go.Size(m)
}
func (m *Config_Generator_Go) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Go.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Go proto.InternalMessageInfo

func (m *Config_Generator_Go) GetPlugins() []Config_Generator_Go_Plugins {
	if m != nil {
		return m.Plugins
	}
	return nil
}

func (m *Config_Generator_Go) GetPaths() Config_Generator_Paths {
	if m != nil {
		return m.Paths
	}
	return Config_Generator_Import
}

func (m *Config_Generator_Go) GetAnnotateCode() bool {
	if m != nil {
		return m.AnnotateCode
	}
	return false
}

type Config_Generator_Micro struct {
	Paths                Config_Generator_Paths `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Config_Generator_Micro) Reset()         { *m = Config_Generator_Micro{} }
func (m *Config_Generator_Micro) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Micro) ProtoMessage()    {}
func (*Config_Generator_Micro) Descriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 2, 2}
}

func (m *Config_Generator_Micro) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Micro.Unmarshal(m, b)
}
func (m *Config_Generator_Micro) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Micro.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Micro) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Micro.Merge(m, src)
}
func (m *Config_Generator_Micro) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Micro.Size(m)
}
func (m *Config_Generator_Micro) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Micro.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Micro proto.InternalMessageInfo

func (m *Config_Generator_Micro) GetPaths() Config_Generator_Paths {
	if m != nil {
		return m.Paths
	}
	return Config_Generator_Import
}

type Config_Generator_Grpc_Gateway struct {
	Paths                Config_Generator_Paths `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
	RegisterFuncSuffix   string                 `protobuf:"bytes,3,opt,name=register_func_suffix,json=registerFuncSuffix,proto3" json:"register_func_suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Config_Generator_Grpc_Gateway) Reset()         { *m = Config_Generator_Grpc_Gateway{} }
func (m *Config_Generator_Grpc_Gateway) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Grpc_Gateway) ProtoMessage()    {}
func (*Config_Generator_Grpc_Gateway) Descriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 2, 3}
}

func (m *Config_Generator_Grpc_Gateway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Grpc_Gateway.Unmarshal(m, b)
}
func (m *Config_Generator_Grpc_Gateway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Grpc_Gateway.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Grpc_Gateway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Grpc_Gateway.Merge(m, src)
}
func (m *Config_Generator_Grpc_Gateway) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Grpc_Gateway.Size(m)
}
func (m *Config_Generator_Grpc_Gateway) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Grpc_Gateway.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Grpc_Gateway proto.InternalMessageInfo

func (m *Config_Generator_Grpc_Gateway) GetPaths() Config_Generator_Paths {
	if m != nil {
		return m.Paths
	}
	return Config_Generator_Import
}

func (m *Config_Generator_Grpc_Gateway) GetRegisterFuncSuffix() string {
	if m != nil {
		return m.RegisterFuncSuffix
	}
	return ""
}

type Config_Generator_Swagger struct {
	Logtostderr          bool     `protobuf:"varint,1,opt,name=logtostderr,proto3" json:"logtostderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config_Generator_Swagger) Reset()         { *m = Config_Generator_Swagger{} }
func (m *Config_Generator_Swagger) String() string { return proto.CompactTextString(m) }
func (*Config_Generator_Swagger) ProtoMessage()    {}
func (*Config_Generator_Swagger) Descriptor() ([]byte, []int) {
	return fileDescriptor_738f7b83cb645dfe, []int{0, 2, 4}
}

func (m *Config_Generator_Swagger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Generator_Swagger.Unmarshal(m, b)
}
func (m *Config_Generator_Swagger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Generator_Swagger.Marshal(b, m, deterministic)
}
func (m *Config_Generator_Swagger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Generator_Swagger.Merge(m, src)
}
func (m *Config_Generator_Swagger) XXX_Size() int {
	return xxx_messageInfo_Config_Generator_Swagger.Size(m)
}
func (m *Config_Generator_Swagger) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Generator_Swagger.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Generator_Swagger proto.InternalMessageInfo

func (m *Config_Generator_Swagger) GetLogtostderr() bool {
	if m != nil {
		return m.Logtostderr
	}
	return false
}

func init() {
	proto.RegisterEnum("godna.Config_PluginOutDir_OutType", Config_PluginOutDir_OutType_name, Config_PluginOutDir_OutType_value)
	proto.RegisterEnum("godna.Config_Pass_Command", Config_Pass_Command_name, Config_Pass_Command_value)
	proto.RegisterEnum("godna.Config_Generator_Paths", Config_Generator_Paths_name, Config_Generator_Paths_value)
	proto.RegisterEnum("godna.Config_Generator_Go_Plugins", Config_Generator_Go_Plugins_name, Config_Generator_Go_Plugins_value)
	proto.RegisterType((*Config)(nil), "godna.Config")
	proto.RegisterType((*Config_PluginOutDir)(nil), "godna.Config.PluginOutDir")
	proto.RegisterType((*Config_Pass)(nil), "godna.Config.Pass")
	proto.RegisterType((*Config_Generator)(nil), "godna.Config.Generator")
	proto.RegisterType((*Config_Generator_Plugin)(nil), "godna.Config.Generator.Plugin")
	proto.RegisterType((*Config_Generator_Go)(nil), "godna.Config.Generator.Go")
	proto.RegisterType((*Config_Generator_Micro)(nil), "godna.Config.Generator.Micro")
	proto.RegisterType((*Config_Generator_Grpc_Gateway)(nil), "godna.Config.Generator.Grpc_Gateway")
	proto.RegisterType((*Config_Generator_Swagger)(nil), "godna.Config.Generator.Swagger")
}

func init() { proto.RegisterFile("dna/config/config.v1.proto", fileDescriptor_738f7b83cb645dfe) }

var fileDescriptor_738f7b83cb645dfe = []byte{
	// 1329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5d, 0x6f, 0x1b, 0x45,
	0x17, 0xf6, 0x26, 0xf1, 0xd7, 0x38, 0x6f, 0xeb, 0x77, 0xde, 0x57, 0x62, 0x65, 0xa9, 0x30, 0x72,
	0x41, 0x09, 0xaa, 0xbd, 0x4e, 0x53, 0x15, 0x2e, 0x68, 0x25, 0xf2, 0xe1, 0x3a, 0x2b, 0xd5, 0x76,
	0x98, 0x18, 0x09, 0xa8, 0xaa, 0x65, 0xb2, 0x3b, 0x5e, 0x0f, 0xec, 0xee, 0x6c, 0x67, 0x66, 0x9d,
	0x5a, 0x42, 0x82, 0x1f, 0xc0, 0xaf, 0xe0, 0x37, 0x98, 0xab, 0x72, 0xcb, 0x2d, 0x37, 0xfc, 0x1b,
	0xab, 0x17, 0x68, 0x66, 0xd7, 0x4d, 0xa0, 0xb2, 0x84, 0x7a, 0x93, 0xcc, 0xc7, 0x39, 0xcf, 0x39,
	0xe7, 0x39, 0xcf, 0x99, 0x35, 0x68, 0x05, 0x09, 0xe9, 0xf9, 0x3c, 0x99, 0xb2, 0xb0, 0xf8, 0xe7,
	0xcc, 0xef, 0x3b, 0xa9, 0xe0, 0x8a, 0xc3, 0x72, 0xc8, 0x83, 0x84, 0xb4, 0x5a, 0x07, 0x07, 0x07,
	0x07, 0x17, 0x93, 0x31, 0xee, 0xf7, 0xe6, 0x24, 0x62, 0x01, 0x51, 0x8c, 0x27, 0xb9, 0x49, 0xfb,
	0x37, 0x08, 0x2a, 0x27, 0xc6, 0x0d, 0x46, 0x00, 0xcc, 0xb8, 0x54, 0x1e, 0xbf, 0x4a, 0xa8, 0xb0,
	0x2d, 0x64, 0xed, 0xd7, 0x8f, 0x87, 0xab, 0xa5, 0xed, 0xea, 0x53, 0x44, 0x92, 0x00, 0x99, 0x1b,
	0xc4, 0xa7, 0x48, 0xcd, 0x28, 0x12, 0x34, 0xe5, 0xeb, 0x75, 0x48, 0x13, 0x2a, 0x88, 0xa2, 0x01,
	0xf2, 0x79, 0x40, 0x11, 0x0d, 0x1d, 0x14, 0x32, 0x35, 0xcb, 0x2e, 0x1d, 0x9f, 0xc7, 0xbd, 0x98,
	0xf9, 0x82, 0x4b, 0x3e, 0x55, 0xb8, 0xae, 0xa1, 0xc6, 0x1a, 0x05, 0x0e, 0x41, 0x5d, 0x23, 0x78,
	0x09, 0x89, 0xa9, 0xbd, 0x65, 0x82, 0x1d, 0xac, 0x96, 0x76, 0xc7, 0xc0, 0xea, 0xc3, 0x8d, 0xd8,
	0x28, 0xe4, 0xdd, 0xb9, 0xd4, 0x1b, 0x5c, 0xd3, 0xd6, 0x23, 0x12, 0x53, 0x38, 0x06, 0x35, 0x96,
	0xf8, 0x51, 0x16, 0x50, 0x69, 0x6f, 0xa3, 0xed, 0xfd, 0xfa, 0xf1, 0x83, 0xd5, 0xd2, 0xee, 0x99,
	0x22, 0x7d, 0x94, 0x12, 0x35, 0x43, 0x5d, 0x57, 0x3b, 0x3f, 0x43, 0x7b, 0x8e, 0x73, 0x9d, 0x52,
	0x57, 0xd3, 0x37, 0xa7, 0x49, 0xc0, 0xc5, 0x1e, 0x7a, 0x8e, 0xdf, 0x80, 0xc0, 0x00, 0xd4, 0x04,
	0x8d, 0x3c, 0x16, 0xa7, 0xd2, 0xde, 0x31, 0x80, 0xee, 0x6a, 0x69, 0xf7, 0x53, 0x41, 0xa7, 0xec,
	0xa5, 0xce, 0x2d, 0xe4, 0x4e, 0xcc, 0x03, 0x14, 0x71, 0x9f, 0x44, 0x9a, 0x8c, 0x88, 0xf8, 0x34,
	0xa6, 0x89, 0x92, 0x4e, 0x11, 0x46, 0x52, 0x31, 0x67, 0x3e, 0x95, 0xdd, 0x3d, 0xf4, 0x1c, 0x75,
	0x91, 0xe2, 0x01, 0x47, 0x82, 0xc6, 0x7c, 0x4e, 0x71, 0x55, 0xd0, 0xc8, 0x8d, 0x53, 0x09, 0xbf,
	0x05, 0x55, 0x41, 0x5f, 0x64, 0x4c, 0x50, 0xbb, 0x6c, 0x82, 0x3c, 0x59, 0x2d, 0xed, 0xe3, 0x88,
	0x49, 0x95, 0x87, 0x40, 0x3a, 0x04, 0x0d, 0x98, 0x42, 0xdd, 0xc2, 0xee, 0x71, 0x81, 0x7e, 0x83,
	0xdf, 0x90, 0x47, 0x24, 0x09, 0x5f, 0xf4, 0x5e, 0x7c, 0x3e, 0xbf, 0xef, 0x1c, 0x38, 0x9f, 0xea,
	0x42, 0xd6, 0xb0, 0xf0, 0x7b, 0x50, 0x95, 0xc2, 0xf7, 0x02, 0x26, 0xec, 0x8a, 0x61, 0x19, 0xaf,
	0x96, 0xf6, 0x48, 0xf2, 0x4c, 0xf8, 0x14, 0x05, 0x4c, 0x50, 0x5f, 0x71, 0xb1, 0xd0, 0xa0, 0x6f,
	0xd1, 0x22, 0x15, 0x17, 0x54, 0x53, 0xf8, 0x1d, 0xf5, 0x15, 0xea, 0xa2, 0x84, 0x2b, 0xaa, 0xff,
	0xa0, 0x82, 0xa4, 0x00, 0x11, 0x89, 0x08, 0xea, 0xba, 0xb8, 0x22, 0x85, 0x7f, 0xca, 0x04, 0x7c,
	0x6d, 0x81, 0x9d, 0x94, 0x48, 0x69, 0xd7, 0xd0, 0xf6, 0x7e, 0xe3, 0x10, 0x3a, 0x46, 0x80, 0x4e,
	0x2e, 0x30, 0xe7, 0x9c, 0x48, 0x79, 0xfc, 0xa7, 0xb5, 0x5a, 0xda, 0x7f, 0x58, 0x3e, 0x8f, 0x63,
	0x9e, 0x20, 0x49, 0x53, 0x92, 0x37, 0x77, 0x5d, 0xb3, 0xbe, 0x20, 0x49, 0x20, 0x91, 0xe2, 0x48,
	0x64, 0x89, 0x83, 0xce, 0xb9, 0x94, 0xec, 0x32, 0xa2, 0xd7, 0x37, 0x44, 0x50, 0x94, 0x37, 0xb6,
	0x13, 0xf3, 0x80, 0x25, 0x4c, 0xe9, 0xff, 0x45, 0xc1, 0xf9, 0xd2, 0x74, 0x43, 0x2f, 0x15, 0x0b,
	0x16, 0x9d, 0x90, 0x29, 0x45, 0x42, 0xb4, 0x1f, 0xd0, 0x29, 0xc9, 0x22, 0x85, 0x9e, 0xb5, 0xff,
	0x8d, 0x7b, 0xbb, 0x83, 0xda, 0x05, 0x82, 0x5e, 0xe6, 0x20, 0xc5, 0x61, 0x61, 0x6d, 0x9a, 0xdf,
	0x7e, 0xfe, 0x31, 0x36, 0x55, 0xc3, 0x5f, 0x2c, 0xd0, 0x48, 0xa3, 0x2c, 0x64, 0x89, 0xa7, 0x15,
	0x67, 0xd7, 0x4d, 0x4b, 0x7f, 0xd2, 0x15, 0xff, 0xa0, 0x55, 0x6a, 0x86, 0xc8, 0x68, 0x91, 0x4f,
	0x11, 0x41, 0xb9, 0x69, 0xa8, 0xb9, 0xcf, 0xf3, 0xe9, 0x86, 0x34, 0xe9, 0x8e, 0x8e, 0x86, 0xfd,
	0xc7, 0xda, 0xa8, 0xa7, 0x78, 0x2f, 0x5e, 0x5c, 0xb2, 0x84, 0x88, 0x85, 0x83, 0x86, 0x99, 0x3f,
	0x43, 0x24, 0x92, 0x1c, 0xc9, 0x94, 0xfa, 0x6c, 0xba, 0x40, 0xdd, 0x6e, 0x31, 0x1a, 0x5c, 0x74,
	0x50, 0xc0, 0xa9, 0xcc, 0x7b, 0x13, 0xa7, 0xd1, 0x02, 0x31, 0x85, 0x10, 0x93, 0x28, 0x15, 0x54,
	0xd2, 0x44, 0x61, 0x90, 0x87, 0x3a, 0x27, 0x6a, 0x06, 0x5f, 0x59, 0xe0, 0xbf, 0x45, 0x92, 0x3c,
	0x53, 0x69, 0xa6, 0x8c, 0x36, 0x80, 0x69, 0x58, 0xeb, 0x1f, 0x0d, 0x33, 0x66, 0xe3, 0x4c, 0x9d,
	0x32, 0x71, 0x2c, 0x57, 0x4b, 0x9b, 0xe7, 0x1e, 0x37, 0x74, 0x33, 0xe5, 0xc2, 0x4c, 0x69, 0x8e,
	0x98, 0x6b, 0x7f, 0x2f, 0xbd, 0xdc, 0x33, 0xa5, 0xee, 0x71, 0x92, 0xb2, 0x3d, 0x63, 0x73, 0xdf,
	0x41, 0x03, 0xde, 0x41, 0x03, 0x91, 0xfa, 0x1d, 0x34, 0xd4, 0x32, 0x33, 0x16, 0x7d, 0x9f, 0xcb,
	0x85, 0xa2, 0x71, 0x77, 0x40, 0x14, 0xbd, 0x22, 0x0b, 0x73, 0x78, 0xe8, 0xa0, 0x8b, 0x2b, 0x12,
	0x86, 0x54, 0xe0, 0xdb, 0xe9, 0x3a, 0x85, 0xd4, 0x64, 0xd1, 0xfa, 0xdd, 0x02, 0xbb, 0x37, 0xd3,
	0x82, 0x50, 0x2b, 0x4e, 0xcd, 0xf2, 0xf7, 0x0a, 0x9b, 0x35, 0x7c, 0x0c, 0x6a, 0x3c, 0x53, 0x9e,
	0x5a, 0xa4, 0xf9, 0xd3, 0x72, 0xeb, 0xb0, 0xbd, 0xb9, 0x30, 0x67, 0x9c, 0xa9, 0xc9, 0x22, 0xa5,
	0xb8, 0xca, 0xf3, 0x05, 0x7c, 0x08, 0xea, 0x6f, 0x98, 0x35, 0x8f, 0x49, 0xe3, 0xf0, 0xbd, 0xbf,
	0xfb, 0x0f, 0xd6, 0xd7, 0xf8, 0xda, 0xb2, 0x7d, 0x0f, 0x54, 0x0b, 0x28, 0xf8, 0x3f, 0x70, 0x7b,
	0x34, 0x9e, 0x9c, 0xb9, 0xa3, 0x81, 0x77, 0x71, 0xde, 0x3f, 0x71, 0x8f, 0x9e, 0x36, 0x4b, 0xb0,
	0x01, 0xaa, 0x83, 0xb1, 0x37, 0x1c, 0x9f, 0x5e, 0x34, 0xad, 0xd6, 0xaf, 0x16, 0xd8, 0xd1, 0xf3,
	0x00, 0x3b, 0x60, 0xdb, 0x8f, 0x03, 0xdb, 0x42, 0xdb, 0xfb, 0xb7, 0xde, 0xe2, 0x9f, 0x48, 0xe9,
	0x9c, 0xe4, 0xb2, 0xc7, 0xda, 0xac, 0xfd, 0x23, 0xa8, 0x16, 0x7b, 0x58, 0x03, 0x3b, 0xa3, 0xf1,
	0xa8, 0xdf, 0x2c, 0x41, 0x00, 0x2a, 0xe7, 0x78, 0x3c, 0x19, 0x9f, 0x34, 0x2d, 0xb8, 0x0b, 0x6a,
	0xc3, 0xf1, 0xa9, 0xe7, 0x8e, 0xdc, 0x49, 0x73, 0x0b, 0xde, 0x06, 0x0d, 0xbd, 0xc3, 0xfd, 0x2f,
	0xbe, 0x74, 0x71, 0xbf, 0xb9, 0x7d, 0x7d, 0x70, 0xfe, 0xf4, 0xe8, 0xa4, 0xdf, 0xdc, 0x59, 0xdb,
	0x4f, 0xdc, 0xd3, 0xaf, 0x9b, 0x65, 0x9d, 0xf7, 0xc0, 0x9d, 0x78, 0x47, 0xa7, 0xa7, 0xde, 0xa8,
	0xff, 0xd5, 0x64, 0x72, 0x34, 0x68, 0x56, 0x4c, 0xde, 0xee, 0xc4, 0xd3, 0x9b, 0x6a, 0xeb, 0xe7,
	0x0a, 0xa8, 0xbf, 0xa9, 0x1e, 0x7e, 0x02, 0x2a, 0x79, 0x83, 0x0c, 0xfd, 0x8d, 0xc3, 0xf7, 0x37,
	0xd0, 0x54, 0x10, 0x8e, 0x0b, 0xeb, 0xd6, 0x6b, 0x0b, 0x54, 0xf2, 0x23, 0xd8, 0x01, 0x5b, 0x21,
	0x2f, 0xdc, 0x5b, 0x9b, 0xdc, 0x07, 0xfc, 0xac, 0x84, 0xb7, 0x42, 0x0e, 0x1f, 0x82, 0xb2, 0x79,
	0xa3, 0x4c, 0x5b, 0x1b, 0x87, 0x77, 0x36, 0x39, 0x18, 0x85, 0x9d, 0x95, 0x70, 0x6e, 0x0d, 0x5d,
	0xb0, 0x1b, 0x8a, 0xd4, 0xf7, 0xc2, 0x5c, 0x65, 0xf6, 0xb6, 0xf1, 0xfe, 0x70, 0x63, 0x38, 0x6d,
	0x5b, 0x28, 0xf2, 0xac, 0x84, 0x1b, 0xda, 0xb7, 0xd8, 0xc2, 0xcf, 0x40, 0x55, 0xe6, 0xe2, 0xb4,
	0x77, 0x0c, 0xca, 0x07, 0x9b, 0x50, 0x0a, 0x0d, 0x9f, 0x95, 0xf0, 0xda, 0xe3, 0xb8, 0x6c, 0x9a,
	0xdd, 0x7a, 0x65, 0x81, 0xad, 0x01, 0x87, 0x8f, 0x40, 0xb5, 0x18, 0x9b, 0xa2, 0xfd, 0xed, 0xcd,
	0xf5, 0x17, 0x0c, 0x4a, 0xbc, 0x76, 0x81, 0x0f, 0x40, 0x59, 0x8b, 0x5d, 0x16, 0x0a, 0xdf, 0x48,
	0x85, 0x1e, 0x7a, 0x89, 0x73, 0x5b, 0x78, 0x17, 0xfc, 0x87, 0x24, 0x09, 0x57, 0x44, 0x51, 0x4f,
	0x7f, 0x41, 0x4d, 0x0d, 0x35, 0xbc, 0xbb, 0x3e, 0x3c, 0xe1, 0x01, 0x6d, 0xdf, 0x01, 0xd5, 0x22,
	0x9a, 0x11, 0x19, 0x4f, 0x68, 0xb3, 0xa4, 0x57, 0x9a, 0x96, 0xa6, 0xd5, 0x7a, 0x04, 0xca, 0x86,
	0xde, 0x77, 0xca, 0xa0, 0x95, 0x81, 0xdd, 0x9b, 0xf4, 0xbe, 0x5b, 0x19, 0x07, 0xe0, 0xff, 0x82,
	0x86, 0x4c, 0x2a, 0x2a, 0xbc, 0x69, 0x96, 0xf8, 0x9e, 0xcc, 0xa6, 0x53, 0xf6, 0xd2, 0xf4, 0xb5,
	0x8e, 0xe1, 0xfa, 0xee, 0x49, 0x96, 0xf8, 0x17, 0xe6, 0xa6, 0x75, 0x0f, 0x54, 0x8b, 0x7e, 0x40,
	0x04, 0x1a, 0x11, 0x0f, 0x15, 0x97, 0x2a, 0xa0, 0x22, 0xff, 0xa1, 0x53, 0xc3, 0x37, 0x8f, 0xda,
	0xfb, 0xa0, 0x6c, 0xc2, 0xe9, 0xc9, 0x72, 0xe3, 0x94, 0x0b, 0xd5, 0x2c, 0xe9, 0xd9, 0xb8, 0x30,
	0x5f, 0x4d, 0x0f, 0xd3, 0x88, 0x28, 0x36, 0xa7, 0x4d, 0xeb, 0xf8, 0xa3, 0x6f, 0xee, 0xde, 0xf8,
	0x10, 0x5f, 0xbd, 0x64, 0xbc, 0x67, 0xf2, 0xef, 0xa5, 0x97, 0xbd, 0xeb, 0x1f, 0x66, 0x97, 0x15,
	0xf3, 0xbe, 0x3f, 0xf8, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x17, 0xdb, 0x1a, 0xad, 0x09, 0x00,
	0x00,
}
