// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: config/config.v1.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/wxio/godna/pb/extensions/store"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package
