// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.11.4
// source: config.v1.proto

package config

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/wxio/godna/pb/extensions/store"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//
type Config_PluginOutDir_OutType int32

const (
	Config_PluginOutDir_NOTHING_SPECIAL Config_PluginOutDir_OutType = 0
	Config_PluginOutDir_GO_MODS         Config_PluginOutDir_OutType = 1
)

// Enum value maps for Config_PluginOutDir_OutType.
var (
	Config_PluginOutDir_OutType_name = map[int32]string{
		0: "NOTHING_SPECIAL",
		1: "GO_MODS",
	}
	Config_PluginOutDir_OutType_value = map[string]int32{
		"NOTHING_SPECIAL": 0,
		"GO_MODS":         1,
	}
)

func (x Config_PluginOutDir_OutType) Enum() *Config_PluginOutDir_OutType {
	p := new(Config_PluginOutDir_OutType)
	*p = x
	return p
}

func (x Config_PluginOutDir_OutType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_PluginOutDir_OutType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_proto_enumTypes[0].Descriptor()
}

func (Config_PluginOutDir_OutType) Type() protoreflect.EnumType {
	return &file_config_v1_proto_enumTypes[0]
}

func (x Config_PluginOutDir_OutType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_PluginOutDir_OutType.Descriptor instead.
func (Config_PluginOutDir_OutType) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 0, 0}
}

//
type Config_Pass_Command int32

const (
	Config_Pass_NONE            Config_Pass_Command = 0
	Config_Pass_PROTOC          Config_Pass_Command = 1
	Config_Pass_MOD_INIT        Config_Pass_Command = 2
	Config_Pass_MOD_REQUIRE     Config_Pass_Command = 3
	Config_Pass_MOD_REPLACE     Config_Pass_Command = 4
	Config_Pass_MOD_TIDY        Config_Pass_Command = 5
	Config_Pass_GIT_ADD_NEXTTAG Config_Pass_Command = 6
	Config_Pass_GIT_TAG         Config_Pass_Command = 7
)

// Enum value maps for Config_Pass_Command.
var (
	Config_Pass_Command_name = map[int32]string{
		0: "NONE",
		1: "PROTOC",
		2: "MOD_INIT",
		3: "MOD_REQUIRE",
		4: "MOD_REPLACE",
		5: "MOD_TIDY",
		6: "GIT_ADD_NEXTTAG",
		7: "GIT_TAG",
	}
	Config_Pass_Command_value = map[string]int32{
		"NONE":            0,
		"PROTOC":          1,
		"MOD_INIT":        2,
		"MOD_REQUIRE":     3,
		"MOD_REPLACE":     4,
		"MOD_TIDY":        5,
		"GIT_ADD_NEXTTAG": 6,
		"GIT_TAG":         7,
	}
)

func (x Config_Pass_Command) Enum() *Config_Pass_Command {
	p := new(Config_Pass_Command)
	*p = x
	return p
}

func (x Config_Pass_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Pass_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_proto_enumTypes[1].Descriptor()
}

func (Config_Pass_Command) Type() protoreflect.EnumType {
	return &file_config_v1_proto_enumTypes[1]
}

func (x Config_Pass_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Pass_Command.Descriptor instead.
func (Config_Pass_Command) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Config_Generator_Paths int32

const (
	Config_Generator_Import          Config_Generator_Paths = 0
	Config_Generator_Source_Relative Config_Generator_Paths = 1
)

// Enum value maps for Config_Generator_Paths.
var (
	Config_Generator_Paths_name = map[int32]string{
		0: "Import",
		1: "Source_Relative",
	}
	Config_Generator_Paths_value = map[string]int32{
		"Import":          0,
		"Source_Relative": 1,
	}
)

func (x Config_Generator_Paths) Enum() *Config_Generator_Paths {
	p := new(Config_Generator_Paths)
	*p = x
	return p
}

func (x Config_Generator_Paths) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Generator_Paths) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_proto_enumTypes[2].Descriptor()
}

func (Config_Generator_Paths) Type() protoreflect.EnumType {
	return &file_config_v1_proto_enumTypes[2]
}

func (x Config_Generator_Paths) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Generator_Paths.Descriptor instead.
func (Config_Generator_Paths) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 2, 0}
}

// map<string,string> importMap = 5;
//
type Config_Generator_Go_Plugins int32

const (
	Config_Generator_Go_None Config_Generator_Go_Plugins = 0
	Config_Generator_Go_Grpc Config_Generator_Go_Plugins = 1
)

// Enum value maps for Config_Generator_Go_Plugins.
var (
	Config_Generator_Go_Plugins_name = map[int32]string{
		0: "None",
		1: "Grpc",
	}
	Config_Generator_Go_Plugins_value = map[string]int32{
		"None": 0,
		"Grpc": 1,
	}
)

func (x Config_Generator_Go_Plugins) Enum() *Config_Generator_Go_Plugins {
	p := new(Config_Generator_Go_Plugins)
	*p = x
	return p
}

func (x Config_Generator_Go_Plugins) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Generator_Go_Plugins) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v1_proto_enumTypes[3].Descriptor()
}

func (Config_Generator_Go_Plugins) Type() protoreflect.EnumType {
	return &file_config_v1_proto_enumTypes[3]
}

func (x Config_Generator_Go_Plugins) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Generator_Go_Plugins.Descriptor instead.
func (Config_Generator_Go_Plugins) EnumDescriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 2, 1, 0}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string   host_owner              = 1
	// [(wxio.dna.help) = "host and owner of the repo of the generated code eg. github.com/microsoft"];
	// //TODO protobuf validators eg [(validator.maditory) = true]
	// string   repo_name               = 2
	// [(wxio.dna.help) = "repo name of the generated code eg go-vscode"];
	Includes []string `protobuf:"bytes,3,rep,name=includes,proto3" json:"includes,omitempty"`
	Require  []string `protobuf:"bytes,5,rep,name=require,proto3" json:"require,omitempty"`
	SrcDir   string   `protobuf:"bytes,6,opt,name=src_dir,json=srcDir,proto3" json:"src_dir,omitempty"`
	// repeated Pass pass            = 8
	// [(wxio.dna.help) = "common separated list of commands to run. Possible commands are protoc,modinit,modrequire,modreplace,modtidy,gittag (default [\"protoc,modinit,modrequire,modreplace\", \"modtidy\", \"gittag\", \"modrequirelocal\"])"];
	// repeated string plugin_path          = 9
	// [(wxio.dna.help) = "Name and path of a pluging eg protoc-gen-NAME=path/to/mybinary. Much also specify --generator, does not imply it  is present"];
	PluginOutputDir []*Config_PluginOutDir `protobuf:"bytes,10,rep,name=plugin_output_dir,json=pluginOutputDir,proto3" json:"plugin_output_dir,omitempty"`
	GoPackagePrefix string                 `protobuf:"bytes,11,opt,name=go_package_prefix,json=goPackagePrefix,proto3" json:"go_package_prefix,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

func (x *Config) GetRequire() []string {
	if x != nil {
		return x.Require
	}
	return nil
}

func (x *Config) GetSrcDir() string {
	if x != nil {
		return x.SrcDir
	}
	return ""
}

func (x *Config) GetPluginOutputDir() []*Config_PluginOutDir {
	if x != nil {
		return x.PluginOutputDir
	}
	return nil
}

func (x *Config) GetGoPackagePrefix() string {
	if x != nil {
		return x.GoPackagePrefix
	}
	return ""
}

//
type Config_PluginOutDir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string                      `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	OutType   Config_PluginOutDir_OutType `protobuf:"varint,2,opt,name=out_type,json=outType,proto3,enum=godna.Config_PluginOutDir_OutType" json:"out_type,omitempty"`
	Generator []*Config_Generator         `protobuf:"bytes,3,rep,name=generator,proto3" json:"generator,omitempty"`
}

func (x *Config_PluginOutDir) Reset() {
	*x = Config_PluginOutDir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_PluginOutDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_PluginOutDir) ProtoMessage() {}

func (x *Config_PluginOutDir) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_PluginOutDir.ProtoReflect.Descriptor instead.
func (*Config_PluginOutDir) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Config_PluginOutDir) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Config_PluginOutDir) GetOutType() Config_PluginOutDir_OutType {
	if x != nil {
		return x.OutType
	}
	return Config_PluginOutDir_NOTHING_SPECIAL
}

func (x *Config_PluginOutDir) GetGenerator() []*Config_Generator {
	if x != nil {
		return x.Generator
	}
	return nil
}

type Config_Pass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd []Config_Pass_Command `protobuf:"varint,1,rep,packed,name=cmd,proto3,enum=godna.Config_Pass_Command" json:"cmd,omitempty"`
}

func (x *Config_Pass) Reset() {
	*x = Config_Pass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Pass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Pass) ProtoMessage() {}

func (x *Config_Pass) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Pass.ProtoReflect.Descriptor instead.
func (*Config_Pass) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Config_Pass) GetCmd() []Config_Pass_Command {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type Config_Generator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugin *Config_Generator_Plugin `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
}

func (x *Config_Generator) Reset() {
	*x = Config_Generator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Generator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Generator) ProtoMessage() {}

func (x *Config_Generator) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Generator.ProtoReflect.Descriptor instead.
func (*Config_Generator) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Config_Generator) GetPlugin() *Config_Generator_Plugin {
	if x != nil {
		return x.Plugin
	}
	return nil
}

//
type Config_Generator_Plugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Cmd:
	//	*Config_Generator_Plugin_Go
	//	*Config_Generator_Plugin_Micro
	//	*Config_Generator_Plugin_GrpcGateway
	//	*Config_Generator_Plugin_Swagger
	//	*Config_Generator_Plugin_Gotag
	Cmd isConfig_Generator_Plugin_Cmd `protobuf_oneof:"cmd"`
}

func (x *Config_Generator_Plugin) Reset() {
	*x = Config_Generator_Plugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Generator_Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Generator_Plugin) ProtoMessage() {}

func (x *Config_Generator_Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Generator_Plugin.ProtoReflect.Descriptor instead.
func (*Config_Generator_Plugin) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (m *Config_Generator_Plugin) GetCmd() isConfig_Generator_Plugin_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (x *Config_Generator_Plugin) GetGo() *Config_Generator_Go {
	if x, ok := x.GetCmd().(*Config_Generator_Plugin_Go); ok {
		return x.Go
	}
	return nil
}

func (x *Config_Generator_Plugin) GetMicro() *Config_Generator_Micro {
	if x, ok := x.GetCmd().(*Config_Generator_Plugin_Micro); ok {
		return x.Micro
	}
	return nil
}

func (x *Config_Generator_Plugin) GetGrpcGateway() *Config_Generator_Grpc_Gateway {
	if x, ok := x.GetCmd().(*Config_Generator_Plugin_GrpcGateway); ok {
		return x.GrpcGateway
	}
	return nil
}

func (x *Config_Generator_Plugin) GetSwagger() *Config_Generator_Swagger {
	if x, ok := x.GetCmd().(*Config_Generator_Plugin_Swagger); ok {
		return x.Swagger
	}
	return nil
}

func (x *Config_Generator_Plugin) GetGotag() *Config_Generator_Gotag {
	if x, ok := x.GetCmd().(*Config_Generator_Plugin_Gotag); ok {
		return x.Gotag
	}
	return nil
}

type isConfig_Generator_Plugin_Cmd interface {
	isConfig_Generator_Plugin_Cmd()
}

type Config_Generator_Plugin_Go struct {
	Go *Config_Generator_Go `protobuf:"bytes,1,opt,name=go,proto3,oneof"`
}

type Config_Generator_Plugin_Micro struct {
	Micro *Config_Generator_Micro `protobuf:"bytes,2,opt,name=micro,proto3,oneof"`
}

type Config_Generator_Plugin_GrpcGateway struct {
	GrpcGateway *Config_Generator_Grpc_Gateway `protobuf:"bytes,3,opt,name=grpc_gateway,json=grpcGateway,proto3,oneof"`
}

type Config_Generator_Plugin_Swagger struct {
	Swagger *Config_Generator_Swagger `protobuf:"bytes,4,opt,name=swagger,proto3,oneof"`
}

type Config_Generator_Plugin_Gotag struct {
	Gotag *Config_Generator_Gotag `protobuf:"bytes,5,opt,name=gotag,proto3,oneof"`
}

func (*Config_Generator_Plugin_Go) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_Micro) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_GrpcGateway) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_Swagger) isConfig_Generator_Plugin_Cmd() {}

func (*Config_Generator_Plugin_Gotag) isConfig_Generator_Plugin_Cmd() {}

type Config_Generator_Go struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plugins []Config_Generator_Go_Plugins `protobuf:"varint,1,rep,packed,name=plugins,proto3,enum=godna.Config_Generator_Go_Plugins" json:"plugins,omitempty"`
	Paths   Config_Generator_Paths        `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
	// string import_prefix = 3;
	AnnotateCode bool `protobuf:"varint,4,opt,name=annotate_code,json=annotateCode,proto3" json:"annotate_code,omitempty"`
}

func (x *Config_Generator_Go) Reset() {
	*x = Config_Generator_Go{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Generator_Go) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Generator_Go) ProtoMessage() {}

func (x *Config_Generator_Go) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Generator_Go.ProtoReflect.Descriptor instead.
func (*Config_Generator_Go) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Config_Generator_Go) GetPlugins() []Config_Generator_Go_Plugins {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *Config_Generator_Go) GetPaths() Config_Generator_Paths {
	if x != nil {
		return x.Paths
	}
	return Config_Generator_Import
}

func (x *Config_Generator_Go) GetAnnotateCode() bool {
	if x != nil {
		return x.AnnotateCode
	}
	return false
}

type Config_Generator_Micro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths Config_Generator_Paths `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
}

func (x *Config_Generator_Micro) Reset() {
	*x = Config_Generator_Micro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Generator_Micro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Generator_Micro) ProtoMessage() {}

func (x *Config_Generator_Micro) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Generator_Micro.ProtoReflect.Descriptor instead.
func (*Config_Generator_Micro) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 2, 2}
}

func (x *Config_Generator_Micro) GetPaths() Config_Generator_Paths {
	if x != nil {
		return x.Paths
	}
	return Config_Generator_Import
}

type Config_Generator_Gotag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths Config_Generator_Paths `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
}

func (x *Config_Generator_Gotag) Reset() {
	*x = Config_Generator_Gotag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Generator_Gotag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Generator_Gotag) ProtoMessage() {}

func (x *Config_Generator_Gotag) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Generator_Gotag.ProtoReflect.Descriptor instead.
func (*Config_Generator_Gotag) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 2, 3}
}

func (x *Config_Generator_Gotag) GetPaths() Config_Generator_Paths {
	if x != nil {
		return x.Paths
	}
	return Config_Generator_Import
}

type Config_Generator_Grpc_Gateway struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths              Config_Generator_Paths `protobuf:"varint,2,opt,name=paths,proto3,enum=godna.Config_Generator_Paths" json:"paths,omitempty"`
	RegisterFuncSuffix string                 `protobuf:"bytes,3,opt,name=register_func_suffix,json=registerFuncSuffix,proto3" json:"register_func_suffix,omitempty"`
}

func (x *Config_Generator_Grpc_Gateway) Reset() {
	*x = Config_Generator_Grpc_Gateway{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Generator_Grpc_Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Generator_Grpc_Gateway) ProtoMessage() {}

func (x *Config_Generator_Grpc_Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Generator_Grpc_Gateway.ProtoReflect.Descriptor instead.
func (*Config_Generator_Grpc_Gateway) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 2, 4}
}

func (x *Config_Generator_Grpc_Gateway) GetPaths() Config_Generator_Paths {
	if x != nil {
		return x.Paths
	}
	return Config_Generator_Import
}

func (x *Config_Generator_Grpc_Gateway) GetRegisterFuncSuffix() string {
	if x != nil {
		return x.RegisterFuncSuffix
	}
	return ""
}

type Config_Generator_Swagger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logtostderr bool `protobuf:"varint,1,opt,name=logtostderr,proto3" json:"logtostderr,omitempty"`
}

func (x *Config_Generator_Swagger) Reset() {
	*x = Config_Generator_Swagger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Generator_Swagger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Generator_Swagger) ProtoMessage() {}

func (x *Config_Generator_Swagger) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Generator_Swagger.ProtoReflect.Descriptor instead.
func (*Config_Generator_Swagger) Descriptor() ([]byte, []int) {
	return file_config_v1_proto_rawDescGZIP(), []int{0, 2, 5}
}

func (x *Config_Generator_Swagger) GetLogtostderr() bool {
	if x != nil {
		return x.Logtostderr
	}
	return false
}

var File_config_v1_proto protoreflect.FileDescriptor

var file_config_v1_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x1a, 0x25, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x30, 0x30, 0x30, 0x30, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9b, 0x0f, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x4f, 0x0a, 0x08, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x42, 0x33, 0xfa, 0xb4,
	0x18, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x20, 0x70, 0x61, 0x74, 0x68, 0x20, 0x2d, 0x49,
	0x20, 0x65, 0x67, 0x20, 0x5b, 0x20, 0x27, 0x2e, 0x2e, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x6f, 0x66, 0x74, 0x2d, 0x64, 0x6e, 0x61, 0x2f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x27, 0x20,
	0x5d, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73, 0x12, 0x60, 0x0a, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x42, 0x46, 0xfa, 0xb4,
	0x18, 0x42, 0x6c, 0x69, 0x73, 0x74, 0x20, 0x6f, 0x66, 0x20, 0x67, 0x6f, 0x20, 0x6d, 0x6f, 0x64,
	0x20, 0x65, 0x64, 0x69, 0x74, 0x20, 0x2d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x3d, 0x20,
	0x65, 0x67, 0x20, 0x5b, 0x20, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x71, 0x2f, 0x71, 0x40, 0x76, 0x31, 0x2e, 0x30, 0x2e,
	0x37, 0x27, 0x20, 0x5d, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x12, 0x6b, 0x0a,
	0x07, 0x73, 0x72, 0x63, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x52,
	0xfa, 0xb4, 0x18, 0x4e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x20, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x20, 0x65, 0x67, 0x20, 0x2e, 0x2e, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x6f, 0x66, 0x74, 0x2d, 0x64, 0x6e, 0x61, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x20, 0x2d, 0x20, 0x6e, 0x6f, 0x74, 0x65, 0x20, 0x6e, 0x6f,
	0x74, 0x20, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x20, 0x61, 0x73, 0x20, 0x61, 0x20,
	0x2d, 0x49, 0x52, 0x06, 0x73, 0x72, 0x63, 0x44, 0x69, 0x72, 0x12, 0xbb, 0x01, 0x0a, 0x11, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x69, 0x72,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x44,
	0x69, 0x72, 0x42, 0x73, 0xfa, 0xb4, 0x18, 0x6f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x20, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x20, 0x66, 0x6f, 0x72, 0x20, 0x74, 0x68, 0x65,
	0x20, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x20, 0x65, 0x67, 0x20, 0x27, 0x70, 0x62,
	0x27, 0x20, 0x61, 0x6e, 0x64, 0x20, 0x27, 0x6f, 0x61, 0x70, 0x69, 0x27, 0x20, 0x66, 0x6f, 0x72,
	0x20, 0x31, 0x2e, 0x20, 0x47, 0x6f, 0x2c, 0x20, 0x47, 0x72, 0x70, 0x63, 0x2c, 0x20, 0x4d, 0x69,
	0x63, 0x72, 0x6f, 0x20, 0x61, 0x6e, 0x64, 0x20, 0x45, 0x63, 0x6f, 0x73, 0x79, 0x74, 0x65, 0x6d,
	0x2d, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x20, 0x61, 0x6e, 0x64, 0x20, 0x32, 0x2e, 0x20,
	0x53, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x52, 0x0f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x69, 0x72, 0x12, 0xae, 0x01, 0x0a, 0x11, 0x67, 0x6f, 0x5f,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x81, 0x01, 0xfa, 0xb4, 0x18, 0x7d, 0x6d, 0x61, 0x6e, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x3b, 0x20, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x20, 0x6f, 0x66, 0x20,
	0x47, 0x6f, 0x20, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x20, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x20, 0x74, 0x6f, 0x20, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x20, 0x55, 0x73, 0x65,
	0x73, 0x3b, 0x20, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x20, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x20, 0x6e, 0x61, 0x6d, 0x65, 0x2c, 0x20, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x20, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x20, 0x74, 0x6f, 0x20, 0x66, 0x69, 0x6e, 0x64, 0x20, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x20, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x20, 0x66, 0x6f,
	0x72, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x52, 0x0f, 0x67, 0x6f, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x1a, 0xc5, 0x01, 0x0a, 0x0c, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x3d,
	0x0a, 0x08, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x44, 0x69, 0x72, 0x2e, 0x4f, 0x75, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a,
	0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x22, 0x2b, 0x0a, 0x07, 0x4f, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x13, 0x0a, 0x0f, 0x4e, 0x4f, 0x54, 0x48, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x41, 0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x4f, 0x5f, 0x4d, 0x4f, 0x44, 0x53, 0x10,
	0x01, 0x1a, 0xb5, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x03, 0x63, 0x6d,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x22, 0x7f, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x4f, 0x44,
	0x5f, 0x49, 0x4e, 0x49, 0x54, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x4f, 0x44, 0x5f, 0x52,
	0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x4f, 0x44, 0x5f,
	0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x4f, 0x44,
	0x5f, 0x54, 0x49, 0x44, 0x59, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x49, 0x54, 0x5f, 0x41,
	0x44, 0x44, 0x5f, 0x4e, 0x45, 0x58, 0x54, 0x54, 0x41, 0x47, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07,
	0x47, 0x49, 0x54, 0x5f, 0x54, 0x41, 0x47, 0x10, 0x07, 0x1a, 0x81, 0x07, 0x0a, 0x09, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x36, 0x0a, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x1a,
	0xb3, 0x02, 0x0a, 0x06, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x02, 0x67, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x47, 0x6f, 0x48, 0x00, 0x52, 0x02, 0x67, 0x6f, 0x12, 0x35, 0x0a, 0x05, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x12,
	0x49, 0x0a, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47,
	0x72, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x67,
	0x72, 0x70, 0x63, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x3b, 0x0a, 0x07, 0x73, 0x77,
	0x61, 0x67, 0x67, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x6f,
	0x64, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x48, 0x00, 0x52, 0x07,
	0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x05, 0x67, 0x6f, 0x74, 0x61, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x47, 0x6f, 0x74, 0x61, 0x67, 0x48, 0x00, 0x52, 0x05, 0x67, 0x6f, 0x74, 0x61, 0x67, 0x42, 0x05,
	0x0a, 0x03, 0x63, 0x6d, 0x64, 0x1a, 0xbb, 0x01, 0x0a, 0x02, 0x47, 0x6f, 0x12, 0x3c, 0x0a, 0x07,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x22, 0x2e,
	0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x6f, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x73, 0x52, 0x07, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x33, 0x0a, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x64, 0x6e,
	0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x72, 0x70,
	0x63, 0x10, 0x01, 0x1a, 0x3c, 0x0a, 0x05, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x12, 0x33, 0x0a, 0x05,
	0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x67, 0x6f,
	0x64, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68,
	0x73, 0x1a, 0x3c, 0x0a, 0x05, 0x47, 0x6f, 0x74, 0x61, 0x67, 0x12, 0x33, 0x0a, 0x05, 0x70, 0x61,
	0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x64, 0x6e,
	0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x1a,
	0x75, 0x0a, 0x0c, 0x47, 0x72, 0x70, 0x63, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12,
	0x33, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x05, 0x70,
	0x61, 0x74, 0x68, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x66, 0x75, 0x6e, 0x63, 0x5f, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63,
	0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x1a, 0x2b, 0x0a, 0x07, 0x53, 0x77, 0x61, 0x67, 0x67, 0x65,
	0x72, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x74, 0x6f, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x74, 0x6f, 0x73, 0x74, 0x64,
	0x65, 0x72, 0x72, 0x22, 0x28, 0x0a, 0x05, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x10, 0x01, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x78, 0x69, 0x6f,
	0x2f, 0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x6e, 0x61, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_v1_proto_rawDescOnce sync.Once
	file_config_v1_proto_rawDescData = file_config_v1_proto_rawDesc
)

func file_config_v1_proto_rawDescGZIP() []byte {
	file_config_v1_proto_rawDescOnce.Do(func() {
		file_config_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_v1_proto_rawDescData)
	})
	return file_config_v1_proto_rawDescData
}

var file_config_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_config_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_config_v1_proto_goTypes = []interface{}{
	(Config_PluginOutDir_OutType)(0),      // 0: godna.Config.PluginOutDir.OutType
	(Config_Pass_Command)(0),              // 1: godna.Config.Pass.Command
	(Config_Generator_Paths)(0),           // 2: godna.Config.Generator.Paths
	(Config_Generator_Go_Plugins)(0),      // 3: godna.Config.Generator.Go.Plugins
	(*Config)(nil),                        // 4: godna.Config
	(*Config_PluginOutDir)(nil),           // 5: godna.Config.PluginOutDir
	(*Config_Pass)(nil),                   // 6: godna.Config.Pass
	(*Config_Generator)(nil),              // 7: godna.Config.Generator
	(*Config_Generator_Plugin)(nil),       // 8: godna.Config.Generator.Plugin
	(*Config_Generator_Go)(nil),           // 9: godna.Config.Generator.Go
	(*Config_Generator_Micro)(nil),        // 10: godna.Config.Generator.Micro
	(*Config_Generator_Gotag)(nil),        // 11: godna.Config.Generator.Gotag
	(*Config_Generator_Grpc_Gateway)(nil), // 12: godna.Config.Generator.Grpc_Gateway
	(*Config_Generator_Swagger)(nil),      // 13: godna.Config.Generator.Swagger
}
var file_config_v1_proto_depIdxs = []int32{
	5,  // 0: godna.Config.plugin_output_dir:type_name -> godna.Config.PluginOutDir
	0,  // 1: godna.Config.PluginOutDir.out_type:type_name -> godna.Config.PluginOutDir.OutType
	7,  // 2: godna.Config.PluginOutDir.generator:type_name -> godna.Config.Generator
	1,  // 3: godna.Config.Pass.cmd:type_name -> godna.Config.Pass.Command
	8,  // 4: godna.Config.Generator.plugin:type_name -> godna.Config.Generator.Plugin
	9,  // 5: godna.Config.Generator.Plugin.go:type_name -> godna.Config.Generator.Go
	10, // 6: godna.Config.Generator.Plugin.micro:type_name -> godna.Config.Generator.Micro
	12, // 7: godna.Config.Generator.Plugin.grpc_gateway:type_name -> godna.Config.Generator.Grpc_Gateway
	13, // 8: godna.Config.Generator.Plugin.swagger:type_name -> godna.Config.Generator.Swagger
	11, // 9: godna.Config.Generator.Plugin.gotag:type_name -> godna.Config.Generator.Gotag
	3,  // 10: godna.Config.Generator.Go.plugins:type_name -> godna.Config.Generator.Go.Plugins
	2,  // 11: godna.Config.Generator.Go.paths:type_name -> godna.Config.Generator.Paths
	2,  // 12: godna.Config.Generator.Micro.paths:type_name -> godna.Config.Generator.Paths
	2,  // 13: godna.Config.Generator.Gotag.paths:type_name -> godna.Config.Generator.Paths
	2,  // 14: godna.Config.Generator.Grpc_Gateway.paths:type_name -> godna.Config.Generator.Paths
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_config_v1_proto_init() }
func file_config_v1_proto_init() {
	if File_config_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_PluginOutDir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Pass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Generator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Generator_Plugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Generator_Go); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Generator_Micro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Generator_Gotag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Generator_Grpc_Gateway); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Generator_Swagger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_config_v1_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Config_Generator_Plugin_Go)(nil),
		(*Config_Generator_Plugin_Micro)(nil),
		(*Config_Generator_Plugin_GrpcGateway)(nil),
		(*Config_Generator_Plugin_Swagger)(nil),
		(*Config_Generator_Plugin_Gotag)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_v1_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v1_proto_goTypes,
		DependencyIndexes: file_config_v1_proto_depIdxs,
		EnumInfos:         file_config_v1_proto_enumTypes,
		MessageInfos:      file_config_v1_proto_msgTypes,
	}.Build()
	File_config_v1_proto = out.File
	file_config_v1_proto_rawDesc = nil
	file_config_v1_proto_goTypes = nil
	file_config_v1_proto_depIdxs = nil
}
