// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.11.4
// source: source.v1.proto

package source

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/wxio/godna/pb/extensions/store"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DnaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*Module `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *DnaData) Reset() {
	*x = DnaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DnaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnaData) ProtoMessage() {}

func (x *DnaData) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnaData.ProtoReflect.Descriptor instead.
func (*DnaData) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{0}
}

func (x *DnaData) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

type Module struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelDir string `protobuf:"bytes,1,opt,name=RelDir,proto3" json:"RelDir,omitempty"`
	Module string `protobuf:"bytes,2,opt,name=Module,proto3" json:"Module,omitempty"`
}

func (x *Module) Reset() {
	*x = Module{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Module) GetRelDir() string {
	if x != nil {
		return x.RelDir
	}
	return ""
}

func (x *Module) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type ModulePlus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Module *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Pkgs   []*PkgWithFilesImports `protobuf:"bytes,2,rep,name=pkgs,proto3" json:"pkgs,omitempty"`
}

func (x *ModulePlus) Reset() {
	*x = ModulePlus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModulePlus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModulePlus) ProtoMessage() {}

func (x *ModulePlus) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModulePlus.ProtoReflect.Descriptor instead.
func (*ModulePlus) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{2}
}

func (x *ModulePlus) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *ModulePlus) GetPkgs() []*PkgWithFilesImports {
	if x != nil {
		return x.Pkgs
	}
	return nil
}

type PkgWithFilesImports struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainingMod string   `protobuf:"bytes,1,opt,name=ContainingMod,proto3" json:"ContainingMod,omitempty"`
	RelDir        string   `protobuf:"bytes,2,opt,name=RelDir,proto3" json:"RelDir,omitempty"`
	Package       string   `protobuf:"bytes,3,opt,name=Package,proto3" json:"Package,omitempty"`
	Files         []string `protobuf:"bytes,4,rep,name=Files,proto3" json:"Files,omitempty"`
	Imports       []string `protobuf:"bytes,5,rep,name=Imports,proto3" json:"Imports,omitempty"`
}

func (x *PkgWithFilesImports) Reset() {
	*x = PkgWithFilesImports{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PkgWithFilesImports) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkgWithFilesImports) ProtoMessage() {}

func (x *PkgWithFilesImports) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkgWithFilesImports.ProtoReflect.Descriptor instead.
func (*PkgWithFilesImports) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{3}
}

func (x *PkgWithFilesImports) GetContainingMod() string {
	if x != nil {
		return x.ContainingMod
	}
	return ""
}

func (x *PkgWithFilesImports) GetRelDir() string {
	if x != nil {
		return x.RelDir
	}
	return ""
}

func (x *PkgWithFilesImports) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *PkgWithFilesImports) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *PkgWithFilesImports) GetImports() []string {
	if x != nil {
		return x.Imports
	}
	return nil
}

type PackageWithPaths struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbsolutePath           string               `protobuf:"bytes,1,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"`
	RelativeFromModulePath string               `protobuf:"bytes,2,opt,name=relative_from_module_path,json=relativeFromModulePath,proto3" json:"relative_from_module_path,omitempty"`
	Dirty                  bool                 `protobuf:"varint,3,opt,name=dirty,proto3" json:"dirty,omitempty"`
	DirtyFiles             []string             `protobuf:"bytes,4,rep,name=dirty_files,json=dirtyFiles,proto3" json:"dirty_files,omitempty"`
	Module                 bool                 `protobuf:"varint,5,opt,name=module,proto3" json:"module,omitempty"`
	Pkg                    *PkgWithFilesImports `protobuf:"bytes,6,opt,name=pkg,proto3" json:"pkg,omitempty"`
}

func (x *PackageWithPaths) Reset() {
	*x = PackageWithPaths{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageWithPaths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageWithPaths) ProtoMessage() {}

func (x *PackageWithPaths) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageWithPaths.ProtoReflect.Descriptor instead.
func (*PackageWithPaths) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{4}
}

func (x *PackageWithPaths) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

func (x *PackageWithPaths) GetRelativeFromModulePath() string {
	if x != nil {
		return x.RelativeFromModulePath
	}
	return ""
}

func (x *PackageWithPaths) GetDirty() bool {
	if x != nil {
		return x.Dirty
	}
	return false
}

func (x *PackageWithPaths) GetDirtyFiles() []string {
	if x != nil {
		return x.DirtyFiles
	}
	return nil
}

func (x *PackageWithPaths) GetModule() bool {
	if x != nil {
		return x.Module
	}
	return false
}

func (x *PackageWithPaths) GetPkg() *PkgWithFilesImports {
	if x != nil {
		return x.Pkg
	}
	return nil
}

type ModuleWithPaths struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Module  *ModulePlus         `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Pkg     *PackageWithPaths   `protobuf:"bytes,2,opt,name=pkg,proto3" json:"pkg,omitempty"`
	Imports []*PackageWithPaths `protobuf:"bytes,3,rep,name=imports,proto3" json:"imports,omitempty"`
}

func (x *ModuleWithPaths) Reset() {
	*x = ModuleWithPaths{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleWithPaths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleWithPaths) ProtoMessage() {}

func (x *ModuleWithPaths) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleWithPaths.ProtoReflect.Descriptor instead.
func (*ModuleWithPaths) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{5}
}

func (x *ModuleWithPaths) GetModule() *ModulePlus {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *ModuleWithPaths) GetPkg() *PackageWithPaths {
	if x != nil {
		return x.Pkg
	}
	return nil
}

func (x *ModuleWithPaths) GetImports() []*PackageWithPaths {
	if x != nil {
		return x.Imports
	}
	return nil
}

type CollectGoModulesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScrDir string `protobuf:"bytes,1,opt,name=ScrDir,proto3" json:"ScrDir,omitempty"`
}

func (x *CollectGoModulesRequest) Reset() {
	*x = CollectGoModulesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectGoModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGoModulesRequest) ProtoMessage() {}

func (x *CollectGoModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGoModulesRequest.ProtoReflect.Descriptor instead.
func (*CollectGoModulesRequest) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{6}
}

func (x *CollectGoModulesRequest) GetScrDir() string {
	if x != nil {
		return x.ScrDir
	}
	return ""
}

type CollectGoModulesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*Module `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *CollectGoModulesResponse) Reset() {
	*x = CollectGoModulesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectGoModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectGoModulesResponse) ProtoMessage() {}

func (x *CollectGoModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectGoModulesResponse.ProtoReflect.Descriptor instead.
func (*CollectGoModulesResponse) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{7}
}

func (x *CollectGoModulesResponse) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

type CollectFilesAndImportsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*Module `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *CollectFilesAndImportsRequest) Reset() {
	*x = CollectFilesAndImportsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectFilesAndImportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectFilesAndImportsRequest) ProtoMessage() {}

func (x *CollectFilesAndImportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectFilesAndImportsRequest.ProtoReflect.Descriptor instead.
func (*CollectFilesAndImportsRequest) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{8}
}

func (x *CollectFilesAndImportsRequest) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

type CollectFilesAndImportsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModulesPlus []*ModulePlus `protobuf:"bytes,1,rep,name=modules_plus,json=modulesPlus,proto3" json:"modules_plus,omitempty"`
}

func (x *CollectFilesAndImportsResponse) Reset() {
	*x = CollectFilesAndImportsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectFilesAndImportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectFilesAndImportsResponse) ProtoMessage() {}

func (x *CollectFilesAndImportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_source_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectFilesAndImportsResponse.ProtoReflect.Descriptor instead.
func (*CollectFilesAndImportsResponse) Descriptor() ([]byte, []int) {
	return file_source_v1_proto_rawDescGZIP(), []int{9}
}

func (x *CollectFilesAndImportsResponse) GetModulesPlus() []*ModulePlus {
	if x != nil {
		return x.ModulesPlus
	}
	return nil
}

var File_source_v1_proto protoreflect.FileDescriptor

var file_source_v1_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x77, 0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x1a, 0x25, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x30,
	0x30, 0x30, 0x30, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x07, 0x44, 0x6e, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x77, 0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61,
	0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x07,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6c, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x65, 0x6c, 0x44, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x22, 0x77, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x50, 0x6c, 0x75, 0x73, 0x12,
	0x2f, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x77, 0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x12, 0x38, 0x0a, 0x04, 0x70, 0x6b, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x77, 0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x50, 0x6b, 0x67, 0x57, 0x69, 0x74, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x52, 0x04, 0x70, 0x6b, 0x67, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x13, 0x50,
	0x6b, 0x67, 0x57, 0x69, 0x74, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x4d, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6c, 0x44,
	0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6c, 0x44, 0x69, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0xf9, 0x01, 0x0a, 0x10, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x39, 0x0a, 0x19, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65,
	0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x69, 0x72, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x64, 0x69, 0x72, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x72, 0x74, 0x79, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x74,
	0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x36,
	0x0a, 0x03, 0x70, 0x6b, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x77, 0x78,
	0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x50, 0x6b,
	0x67, 0x57, 0x69, 0x74, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x52, 0x03, 0x70, 0x6b, 0x67, 0x22, 0xb8, 0x01, 0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x33, 0x0a, 0x06, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x77, 0x78, 0x69,
	0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x50, 0x6c, 0x75, 0x73, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12,
	0x33, 0x0a, 0x03, 0x70, 0x6b, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x77,
	0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x57, 0x69, 0x74, 0x68, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52,
	0x03, 0x70, 0x6b, 0x67, 0x12, 0x3b, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x77, 0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61,
	0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x57,
	0x69, 0x74, 0x68, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x07, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x22, 0x31, 0x0a, 0x17, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x47, 0x6f, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x63, 0x72, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x63,
	0x72, 0x44, 0x69, 0x72, 0x22, 0x4d, 0x0a, 0x18, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x47,
	0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x77, 0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x1d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x77, 0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61,
	0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x07,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x60, 0x0a, 0x1e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x73, 0x5f, 0x70, 0x6c, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x77, 0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x50, 0x6c, 0x75, 0x73, 0x52, 0x0b, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x73, 0x50, 0x6c, 0x75, 0x73, 0x32, 0xf0, 0x01, 0x0a, 0x0a, 0x44, 0x6e,
	0x61, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x67, 0x0a, 0x10, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x47, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x28, 0x2e, 0x77,
	0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x47, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x77, 0x78, 0x69, 0x6f, 0x2e, 0x64, 0x6e,
	0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x47, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x79, 0x0a, 0x16, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x41, 0x6e, 0x64, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x2e, 0x2e, 0x77, 0x78,
	0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x77, 0x78,
	0x69, 0x6f, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x49, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25, 0x5a, 0x23,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x78, 0x69, 0x6f, 0x2f,
	0x67, 0x6f, 0x64, 0x6e, 0x61, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x6e, 0x61, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_source_v1_proto_rawDescOnce sync.Once
	file_source_v1_proto_rawDescData = file_source_v1_proto_rawDesc
)

func file_source_v1_proto_rawDescGZIP() []byte {
	file_source_v1_proto_rawDescOnce.Do(func() {
		file_source_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_source_v1_proto_rawDescData)
	})
	return file_source_v1_proto_rawDescData
}

var file_source_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_source_v1_proto_goTypes = []interface{}{
	(*DnaData)(nil),                        // 0: wxio.dna.source.DnaData
	(*Module)(nil),                         // 1: wxio.dna.source.Module
	(*ModulePlus)(nil),                     // 2: wxio.dna.source.ModulePlus
	(*PkgWithFilesImports)(nil),            // 3: wxio.dna.source.PkgWithFilesImports
	(*PackageWithPaths)(nil),               // 4: wxio.dna.source.PackageWithPaths
	(*ModuleWithPaths)(nil),                // 5: wxio.dna.source.ModuleWithPaths
	(*CollectGoModulesRequest)(nil),        // 6: wxio.dna.source.CollectGoModulesRequest
	(*CollectGoModulesResponse)(nil),       // 7: wxio.dna.source.CollectGoModulesResponse
	(*CollectFilesAndImportsRequest)(nil),  // 8: wxio.dna.source.CollectFilesAndImportsRequest
	(*CollectFilesAndImportsResponse)(nil), // 9: wxio.dna.source.CollectFilesAndImportsResponse
}
var file_source_v1_proto_depIdxs = []int32{
	1,  // 0: wxio.dna.source.DnaData.modules:type_name -> wxio.dna.source.Module
	1,  // 1: wxio.dna.source.ModulePlus.module:type_name -> wxio.dna.source.Module
	3,  // 2: wxio.dna.source.ModulePlus.pkgs:type_name -> wxio.dna.source.PkgWithFilesImports
	3,  // 3: wxio.dna.source.PackageWithPaths.pkg:type_name -> wxio.dna.source.PkgWithFilesImports
	2,  // 4: wxio.dna.source.ModuleWithPaths.module:type_name -> wxio.dna.source.ModulePlus
	4,  // 5: wxio.dna.source.ModuleWithPaths.pkg:type_name -> wxio.dna.source.PackageWithPaths
	4,  // 6: wxio.dna.source.ModuleWithPaths.imports:type_name -> wxio.dna.source.PackageWithPaths
	1,  // 7: wxio.dna.source.CollectGoModulesResponse.modules:type_name -> wxio.dna.source.Module
	1,  // 8: wxio.dna.source.CollectFilesAndImportsRequest.modules:type_name -> wxio.dna.source.Module
	2,  // 9: wxio.dna.source.CollectFilesAndImportsResponse.modules_plus:type_name -> wxio.dna.source.ModulePlus
	6,  // 10: wxio.dna.source.DnaProcess.CollectGoModules:input_type -> wxio.dna.source.CollectGoModulesRequest
	8,  // 11: wxio.dna.source.DnaProcess.CollectFilesAndImports:input_type -> wxio.dna.source.CollectFilesAndImportsRequest
	7,  // 12: wxio.dna.source.DnaProcess.CollectGoModules:output_type -> wxio.dna.source.CollectGoModulesResponse
	9,  // 13: wxio.dna.source.DnaProcess.CollectFilesAndImports:output_type -> wxio.dna.source.CollectFilesAndImportsResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_source_v1_proto_init() }
func file_source_v1_proto_init() {
	if File_source_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_source_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DnaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Module); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModulePlus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PkgWithFilesImports); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageWithPaths); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleWithPaths); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectGoModulesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectGoModulesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectFilesAndImportsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectFilesAndImportsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_source_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_source_v1_proto_goTypes,
		DependencyIndexes: file_source_v1_proto_depIdxs,
		MessageInfos:      file_source_v1_proto_msgTypes,
	}.Build()
	File_source_v1_proto = out.File
	file_source_v1_proto_rawDesc = nil
	file_source_v1_proto_goTypes = nil
	file_source_v1_proto_depIdxs = nil
}
