// Code generated by protoc-gen-go. DO NOT EDIT.
// source: source.v1.proto

package source

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/wxio/godna/pb/extensions/store"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DnaData struct {
	Modules              []*Module `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DnaData) Reset()         { *m = DnaData{} }
func (m *DnaData) String() string { return proto.CompactTextString(m) }
func (*DnaData) ProtoMessage()    {}
func (*DnaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{0}
}

func (m *DnaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DnaData.Unmarshal(m, b)
}
func (m *DnaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DnaData.Marshal(b, m, deterministic)
}
func (m *DnaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DnaData.Merge(m, src)
}
func (m *DnaData) XXX_Size() int {
	return xxx_messageInfo_DnaData.Size(m)
}
func (m *DnaData) XXX_DiscardUnknown() {
	xxx_messageInfo_DnaData.DiscardUnknown(m)
}

var xxx_messageInfo_DnaData proto.InternalMessageInfo

func (m *DnaData) GetModules() []*Module {
	if m != nil {
		return m.Modules
	}
	return nil
}

type Module struct {
	RelDir               string   `protobuf:"bytes,1,opt,name=RelDir,proto3" json:"RelDir,omitempty"`
	Module               string   `protobuf:"bytes,2,opt,name=Module,proto3" json:"Module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{1}
}

func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetRelDir() string {
	if m != nil {
		return m.RelDir
	}
	return ""
}

func (m *Module) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type ModulePlus struct {
	Module               *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Pkgs                 []*PkgWithFilesImports `protobuf:"bytes,2,rep,name=pkgs,proto3" json:"pkgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ModulePlus) Reset()         { *m = ModulePlus{} }
func (m *ModulePlus) String() string { return proto.CompactTextString(m) }
func (*ModulePlus) ProtoMessage()    {}
func (*ModulePlus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{2}
}

func (m *ModulePlus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModulePlus.Unmarshal(m, b)
}
func (m *ModulePlus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModulePlus.Marshal(b, m, deterministic)
}
func (m *ModulePlus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModulePlus.Merge(m, src)
}
func (m *ModulePlus) XXX_Size() int {
	return xxx_messageInfo_ModulePlus.Size(m)
}
func (m *ModulePlus) XXX_DiscardUnknown() {
	xxx_messageInfo_ModulePlus.DiscardUnknown(m)
}

var xxx_messageInfo_ModulePlus proto.InternalMessageInfo

func (m *ModulePlus) GetModule() *Module {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *ModulePlus) GetPkgs() []*PkgWithFilesImports {
	if m != nil {
		return m.Pkgs
	}
	return nil
}

type PkgWithFilesImports struct {
	ContainingMod        string   `protobuf:"bytes,1,opt,name=ContainingMod,proto3" json:"ContainingMod,omitempty"`
	RelDir               string   `protobuf:"bytes,2,opt,name=RelDir,proto3" json:"RelDir,omitempty"`
	Package              string   `protobuf:"bytes,3,opt,name=Package,proto3" json:"Package,omitempty"`
	Files                []string `protobuf:"bytes,4,rep,name=Files,proto3" json:"Files,omitempty"`
	Imports              []string `protobuf:"bytes,5,rep,name=Imports,proto3" json:"Imports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PkgWithFilesImports) Reset()         { *m = PkgWithFilesImports{} }
func (m *PkgWithFilesImports) String() string { return proto.CompactTextString(m) }
func (*PkgWithFilesImports) ProtoMessage()    {}
func (*PkgWithFilesImports) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{3}
}

func (m *PkgWithFilesImports) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgWithFilesImports.Unmarshal(m, b)
}
func (m *PkgWithFilesImports) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgWithFilesImports.Marshal(b, m, deterministic)
}
func (m *PkgWithFilesImports) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgWithFilesImports.Merge(m, src)
}
func (m *PkgWithFilesImports) XXX_Size() int {
	return xxx_messageInfo_PkgWithFilesImports.Size(m)
}
func (m *PkgWithFilesImports) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgWithFilesImports.DiscardUnknown(m)
}

var xxx_messageInfo_PkgWithFilesImports proto.InternalMessageInfo

func (m *PkgWithFilesImports) GetContainingMod() string {
	if m != nil {
		return m.ContainingMod
	}
	return ""
}

func (m *PkgWithFilesImports) GetRelDir() string {
	if m != nil {
		return m.RelDir
	}
	return ""
}

func (m *PkgWithFilesImports) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *PkgWithFilesImports) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *PkgWithFilesImports) GetImports() []string {
	if m != nil {
		return m.Imports
	}
	return nil
}

type PackageWithPaths struct {
	AbsolutePath           string               `protobuf:"bytes,1,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"`
	RelativeFromModulePath string               `protobuf:"bytes,2,opt,name=relative_from_module_path,json=relativeFromModulePath,proto3" json:"relative_from_module_path,omitempty"`
	Dirty                  bool                 `protobuf:"varint,3,opt,name=dirty,proto3" json:"dirty,omitempty"`
	DirtyFiles             []string             `protobuf:"bytes,4,rep,name=dirty_files,json=dirtyFiles,proto3" json:"dirty_files,omitempty"`
	Module                 bool                 `protobuf:"varint,5,opt,name=module,proto3" json:"module,omitempty"`
	Pkg                    *PkgWithFilesImports `protobuf:"bytes,6,opt,name=pkg,proto3" json:"pkg,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *PackageWithPaths) Reset()         { *m = PackageWithPaths{} }
func (m *PackageWithPaths) String() string { return proto.CompactTextString(m) }
func (*PackageWithPaths) ProtoMessage()    {}
func (*PackageWithPaths) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{4}
}

func (m *PackageWithPaths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageWithPaths.Unmarshal(m, b)
}
func (m *PackageWithPaths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageWithPaths.Marshal(b, m, deterministic)
}
func (m *PackageWithPaths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageWithPaths.Merge(m, src)
}
func (m *PackageWithPaths) XXX_Size() int {
	return xxx_messageInfo_PackageWithPaths.Size(m)
}
func (m *PackageWithPaths) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageWithPaths.DiscardUnknown(m)
}

var xxx_messageInfo_PackageWithPaths proto.InternalMessageInfo

func (m *PackageWithPaths) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *PackageWithPaths) GetRelativeFromModulePath() string {
	if m != nil {
		return m.RelativeFromModulePath
	}
	return ""
}

func (m *PackageWithPaths) GetDirty() bool {
	if m != nil {
		return m.Dirty
	}
	return false
}

func (m *PackageWithPaths) GetDirtyFiles() []string {
	if m != nil {
		return m.DirtyFiles
	}
	return nil
}

func (m *PackageWithPaths) GetModule() bool {
	if m != nil {
		return m.Module
	}
	return false
}

func (m *PackageWithPaths) GetPkg() *PkgWithFilesImports {
	if m != nil {
		return m.Pkg
	}
	return nil
}

type ModuleWithPaths struct {
	Module               *ModulePlus         `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Pkg                  *PackageWithPaths   `protobuf:"bytes,2,opt,name=pkg,proto3" json:"pkg,omitempty"`
	Imports              []*PackageWithPaths `protobuf:"bytes,3,rep,name=imports,proto3" json:"imports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ModuleWithPaths) Reset()         { *m = ModuleWithPaths{} }
func (m *ModuleWithPaths) String() string { return proto.CompactTextString(m) }
func (*ModuleWithPaths) ProtoMessage()    {}
func (*ModuleWithPaths) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{5}
}

func (m *ModuleWithPaths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleWithPaths.Unmarshal(m, b)
}
func (m *ModuleWithPaths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleWithPaths.Marshal(b, m, deterministic)
}
func (m *ModuleWithPaths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleWithPaths.Merge(m, src)
}
func (m *ModuleWithPaths) XXX_Size() int {
	return xxx_messageInfo_ModuleWithPaths.Size(m)
}
func (m *ModuleWithPaths) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleWithPaths.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleWithPaths proto.InternalMessageInfo

func (m *ModuleWithPaths) GetModule() *ModulePlus {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *ModuleWithPaths) GetPkg() *PackageWithPaths {
	if m != nil {
		return m.Pkg
	}
	return nil
}

func (m *ModuleWithPaths) GetImports() []*PackageWithPaths {
	if m != nil {
		return m.Imports
	}
	return nil
}

type CollectGoModulesRequest struct {
	ScrDir               string   `protobuf:"bytes,1,opt,name=ScrDir,proto3" json:"ScrDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectGoModulesRequest) Reset()         { *m = CollectGoModulesRequest{} }
func (m *CollectGoModulesRequest) String() string { return proto.CompactTextString(m) }
func (*CollectGoModulesRequest) ProtoMessage()    {}
func (*CollectGoModulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{6}
}

func (m *CollectGoModulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectGoModulesRequest.Unmarshal(m, b)
}
func (m *CollectGoModulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectGoModulesRequest.Marshal(b, m, deterministic)
}
func (m *CollectGoModulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectGoModulesRequest.Merge(m, src)
}
func (m *CollectGoModulesRequest) XXX_Size() int {
	return xxx_messageInfo_CollectGoModulesRequest.Size(m)
}
func (m *CollectGoModulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectGoModulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectGoModulesRequest proto.InternalMessageInfo

func (m *CollectGoModulesRequest) GetScrDir() string {
	if m != nil {
		return m.ScrDir
	}
	return ""
}

type CollectGoModulesResponse struct {
	Modules              []*Module `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CollectGoModulesResponse) Reset()         { *m = CollectGoModulesResponse{} }
func (m *CollectGoModulesResponse) String() string { return proto.CompactTextString(m) }
func (*CollectGoModulesResponse) ProtoMessage()    {}
func (*CollectGoModulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{7}
}

func (m *CollectGoModulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectGoModulesResponse.Unmarshal(m, b)
}
func (m *CollectGoModulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectGoModulesResponse.Marshal(b, m, deterministic)
}
func (m *CollectGoModulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectGoModulesResponse.Merge(m, src)
}
func (m *CollectGoModulesResponse) XXX_Size() int {
	return xxx_messageInfo_CollectGoModulesResponse.Size(m)
}
func (m *CollectGoModulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectGoModulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectGoModulesResponse proto.InternalMessageInfo

func (m *CollectGoModulesResponse) GetModules() []*Module {
	if m != nil {
		return m.Modules
	}
	return nil
}

type CollectFilesAndImportsRequest struct {
	Modules              []*Module `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CollectFilesAndImportsRequest) Reset()         { *m = CollectFilesAndImportsRequest{} }
func (m *CollectFilesAndImportsRequest) String() string { return proto.CompactTextString(m) }
func (*CollectFilesAndImportsRequest) ProtoMessage()    {}
func (*CollectFilesAndImportsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{8}
}

func (m *CollectFilesAndImportsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectFilesAndImportsRequest.Unmarshal(m, b)
}
func (m *CollectFilesAndImportsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectFilesAndImportsRequest.Marshal(b, m, deterministic)
}
func (m *CollectFilesAndImportsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectFilesAndImportsRequest.Merge(m, src)
}
func (m *CollectFilesAndImportsRequest) XXX_Size() int {
	return xxx_messageInfo_CollectFilesAndImportsRequest.Size(m)
}
func (m *CollectFilesAndImportsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectFilesAndImportsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectFilesAndImportsRequest proto.InternalMessageInfo

func (m *CollectFilesAndImportsRequest) GetModules() []*Module {
	if m != nil {
		return m.Modules
	}
	return nil
}

type CollectFilesAndImportsResponse struct {
	ModulesPlus          []*ModulePlus `protobuf:"bytes,1,rep,name=modules_plus,json=modulesPlus,proto3" json:"modules_plus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CollectFilesAndImportsResponse) Reset()         { *m = CollectFilesAndImportsResponse{} }
func (m *CollectFilesAndImportsResponse) String() string { return proto.CompactTextString(m) }
func (*CollectFilesAndImportsResponse) ProtoMessage()    {}
func (*CollectFilesAndImportsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe51ff600ea989f, []int{9}
}

func (m *CollectFilesAndImportsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectFilesAndImportsResponse.Unmarshal(m, b)
}
func (m *CollectFilesAndImportsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectFilesAndImportsResponse.Marshal(b, m, deterministic)
}
func (m *CollectFilesAndImportsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectFilesAndImportsResponse.Merge(m, src)
}
func (m *CollectFilesAndImportsResponse) XXX_Size() int {
	return xxx_messageInfo_CollectFilesAndImportsResponse.Size(m)
}
func (m *CollectFilesAndImportsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectFilesAndImportsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectFilesAndImportsResponse proto.InternalMessageInfo

func (m *CollectFilesAndImportsResponse) GetModulesPlus() []*ModulePlus {
	if m != nil {
		return m.ModulesPlus
	}
	return nil
}

func init() {
	proto.RegisterType((*DnaData)(nil), "wxio.dna.source.DnaData")
	proto.RegisterType((*Module)(nil), "wxio.dna.source.Module")
	proto.RegisterType((*ModulePlus)(nil), "wxio.dna.source.ModulePlus")
	proto.RegisterType((*PkgWithFilesImports)(nil), "wxio.dna.source.PkgWithFilesImports")
	proto.RegisterType((*PackageWithPaths)(nil), "wxio.dna.source.PackageWithPaths")
	proto.RegisterType((*ModuleWithPaths)(nil), "wxio.dna.source.ModuleWithPaths")
	proto.RegisterType((*CollectGoModulesRequest)(nil), "wxio.dna.source.CollectGoModulesRequest")
	proto.RegisterType((*CollectGoModulesResponse)(nil), "wxio.dna.source.CollectGoModulesResponse")
	proto.RegisterType((*CollectFilesAndImportsRequest)(nil), "wxio.dna.source.CollectFilesAndImportsRequest")
	proto.RegisterType((*CollectFilesAndImportsResponse)(nil), "wxio.dna.source.CollectFilesAndImportsResponse")
}

func init() { proto.RegisterFile("source.v1.proto", fileDescriptor_ffe51ff600ea989f) }

var fileDescriptor_ffe51ff600ea989f = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x55, 0xda, 0xb5, 0xfd, 0xed, 0x6e, 0xd3, 0x26, 0xff, 0xa6, 0x2e, 0x0c, 0x01, 0x23, 0xdb,
	0xa4, 0xf2, 0x92, 0xb4, 0xab, 0x84, 0x86, 0x40, 0x48, 0xb0, 0x32, 0xc4, 0x43, 0x45, 0x95, 0x21,
	0x21, 0xf1, 0x52, 0xdc, 0xc4, 0x4b, 0xad, 0xa6, 0x76, 0x88, 0x9d, 0x6e, 0xfb, 0x30, 0x7c, 0x0f,
	0x3e, 0x16, 0xaf, 0xbc, 0xa1, 0xd8, 0xce, 0xe8, 0xfa, 0x67, 0xaa, 0xf6, 0xd4, 0xdc, 0xeb, 0x73,
	0xee, 0x3d, 0xf7, 0x5c, 0xbb, 0xb0, 0x2d, 0x78, 0x96, 0x06, 0xc4, 0x9d, 0xb4, 0xdc, 0x24, 0xe5,
	0x92, 0xa3, 0xed, 0xab, 0x6b, 0xca, 0xdd, 0x90, 0x61, 0x57, 0x9f, 0xec, 0x1f, 0x93, 0x6b, 0x49,
	0x98, 0xa0, 0x9c, 0x09, 0xaf, 0xd9, 0x6c, 0x36, 0x2f, 0xbe, 0x7c, 0xf6, 0x3f, 0x78, 0x13, 0x1c,
	0xd3, 0x10, 0x4b, 0xca, 0x99, 0xe6, 0x39, 0x6f, 0xa0, 0xd6, 0x61, 0xb8, 0x83, 0x25, 0x46, 0x2d,
	0xa8, 0x8d, 0x79, 0x98, 0xc5, 0x44, 0xd8, 0xd6, 0x41, 0xb9, 0xb1, 0x71, 0xb2, 0xe7, 0xce, 0x14,
	0x75, 0xbb, 0xea, 0xdc, 0x2f, 0x70, 0xce, 0x29, 0x54, 0x75, 0x0a, 0xd5, 0xa1, 0xea, 0x93, 0xb8,
	0x43, 0x53, 0xdb, 0x3a, 0xb0, 0x1a, 0xeb, 0xbe, 0x89, 0xf2, 0xbc, 0x46, 0xd8, 0x25, 0x9d, 0xd7,
	0x91, 0x73, 0x05, 0xa0, 0xbf, 0x7a, 0x71, 0x26, 0x90, 0x07, 0x55, 0x5d, 0x52, 0xb1, 0xef, 0xe9,
	0x6c, 0x60, 0xe8, 0x14, 0xd6, 0x92, 0x51, 0x24, 0xec, 0x92, 0x12, 0x7a, 0x34, 0x07, 0xef, 0x8d,
	0xa2, 0xaf, 0x54, 0x0e, 0xcf, 0x69, 0x4c, 0xc4, 0xa7, 0x71, 0xc2, 0x53, 0x29, 0x7c, 0xc5, 0x70,
	0x7e, 0x5a, 0xf0, 0xff, 0x82, 0x53, 0x74, 0x04, 0x5b, 0x67, 0x9c, 0x49, 0x4c, 0x19, 0x65, 0x51,
	0x97, 0x87, 0x66, 0x8e, 0xbb, 0xc9, 0xa9, 0x31, 0x4b, 0x77, 0xc6, 0xb4, 0xa1, 0xd6, 0xc3, 0xc1,
	0x08, 0x47, 0xc4, 0x2e, 0xab, 0x83, 0x22, 0x44, 0xbb, 0x50, 0x51, 0x7d, 0xec, 0xb5, 0x83, 0x72,
	0x63, 0xdd, 0xd7, 0x41, 0x8e, 0x37, 0x8d, 0xed, 0x8a, 0xca, 0x17, 0xa1, 0xf3, 0xc7, 0x82, 0x1d,
	0xc3, 0xcd, 0x35, 0xf6, 0xb0, 0x1c, 0x0a, 0x74, 0x08, 0x5b, 0x78, 0x20, 0x78, 0x9c, 0x49, 0xd2,
	0x4f, 0xb0, 0x1c, 0x1a, 0x71, 0x9b, 0x45, 0x32, 0x47, 0xa1, 0x57, 0xf0, 0x28, 0x25, 0x31, 0x96,
	0x74, 0x42, 0xfa, 0x97, 0x29, 0x1f, 0xf7, 0xb5, 0x57, 0x9a, 0xa0, 0xe5, 0xd6, 0x0b, 0xc0, 0x79,
	0xca, 0xc7, 0xc6, 0xff, 0x9c, 0xba, 0x0b, 0x95, 0x90, 0xa6, 0xf2, 0x46, 0x89, 0xff, 0xcf, 0xd7,
	0x01, 0x7a, 0x06, 0x1b, 0xea, 0xa3, 0x7f, 0x39, 0x35, 0x00, 0xa8, 0x94, 0x9e, 0xa2, 0x7e, 0xbb,
	0xb6, 0x8a, 0xe2, 0x15, 0xdb, 0x79, 0x09, 0xe5, 0x64, 0x14, 0xd9, 0x55, 0xb5, 0xcb, 0xd5, 0x96,
	0x93, 0x13, 0x9c, 0x5f, 0x16, 0x6c, 0x6b, 0x55, 0xff, 0x46, 0x6f, 0xcf, 0x5c, 0x8d, 0xc7, 0x4b,
	0xae, 0x46, 0x7e, 0x8f, 0x6e, 0x05, 0xb4, 0xb5, 0x80, 0x92, 0x62, 0x3c, 0x9f, 0x17, 0x30, 0xe3,
	0xaf, 0xea, 0x8e, 0x5e, 0x43, 0x8d, 0x9a, 0x9d, 0x94, 0xd5, 0xb5, 0x5a, 0x81, 0x58, 0x30, 0x9c,
	0x16, 0xec, 0x9d, 0xf1, 0x38, 0x26, 0x81, 0xfc, 0xc8, 0xb5, 0x20, 0xe1, 0x93, 0x1f, 0x19, 0x11,
	0x32, 0x77, 0xe9, 0x22, 0x48, 0xa7, 0x9e, 0x86, 0x8e, 0x9c, 0x2e, 0xd8, 0xf3, 0x14, 0x91, 0x70,
	0x26, 0xc8, 0x43, 0xde, 0xa2, 0x0f, 0x4f, 0x4c, 0x39, 0x65, 0xec, 0x3b, 0x16, 0x16, 0xde, 0x1a,
	0x1d, 0x0f, 0xa8, 0xf9, 0x1d, 0x9e, 0x2e, 0xab, 0x69, 0x84, 0xbe, 0x85, 0x4d, 0x03, 0xee, 0x27,
	0x71, 0x56, 0x54, 0xbe, 0x77, 0x49, 0x1b, 0x86, 0x90, 0x07, 0x27, 0xbf, 0x2d, 0x80, 0x0e, 0xc3,
	0xbd, 0x94, 0x07, 0x44, 0x08, 0x14, 0xc1, 0xce, 0xac, 0x27, 0xa8, 0x31, 0x57, 0x6c, 0x89, 0xd3,
	0xfb, 0x2f, 0x56, 0x40, 0x1a, 0xdd, 0x37, 0x50, 0x5f, 0x3c, 0x19, 0x72, 0x97, 0x15, 0x59, 0x6c,
	0xeb, 0xbe, 0xb7, 0x32, 0x5e, 0xb7, 0x7e, 0x7f, 0xfc, 0xed, 0x30, 0xa2, 0x72, 0x98, 0x0d, 0xdc,
	0x80, 0x8f, 0xbd, 0x9c, 0xec, 0x45, 0x3c, 0x64, 0xd8, 0x4b, 0x06, 0x5e, 0xfe, 0xa3, 0xab, 0x0c,
	0xaa, 0xea, 0x0f, 0xba, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0xef, 0xfb, 0x8d, 0x24, 0xeb, 0x05,
	0x00, 0x00,
}
