// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dna/source/source.v1.proto

package source

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/wxio/godna/pb/extensions/store"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Source struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0724268c810e1d0, []int{0}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Source)(nil), "wxio.dna.source.Source")
}

func init() { proto.RegisterFile("dna/source/source.v1.proto", fileDescriptor_e0724268c810e1d0) }

var fileDescriptor_e0724268c810e1d0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4a, 0xc9, 0x4b, 0xd4,
	0x2f, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x85, 0x52, 0x7a, 0x65, 0x86, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0xfc, 0xe5, 0x15, 0x99, 0xf9, 0x7a, 0x29, 0x79, 0x89, 0x7a, 0x10, 0x19, 0x29, 0x29,
	0x03, 0x03, 0x03, 0x83, 0xe0, 0x10, 0xff, 0x20, 0x57, 0xfd, 0xb2, 0xc4, 0x9c, 0xcc, 0x94, 0xc4,
	0x92, 0xcc, 0xfc, 0x3c, 0x88, 0x62, 0x25, 0x0e, 0x2e, 0xb6, 0x60, 0xb0, 0x2a, 0x27, 0xd5, 0x28,
	0xe5, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x90, 0x19, 0xfa, 0xe9,
	0xf9, 0x20, 0x6b, 0x0a, 0x92, 0xf4, 0x11, 0xb6, 0x25, 0xb1, 0x81, 0xf5, 0x19, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x04, 0x07, 0xde, 0x4e, 0x82, 0x00, 0x00, 0x00,
}
