// Code generated by protoc-gen-go. DO NOT EDIT.
// source: module_def.proto

package module

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Module struct {
	Gomod                *GoMod   `protobuf:"bytes,1,opt,name=gomod,proto3" json:"gomod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_f03406d9d0fdefdf, []int{0}
}

func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetGomod() *GoMod {
	if m != nil {
		return m.Gomod
	}
	return nil
}

type GoMod struct {
	Module               string   `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoMod) Reset()         { *m = GoMod{} }
func (m *GoMod) String() string { return proto.CompactTextString(m) }
func (*GoMod) ProtoMessage()    {}
func (*GoMod) Descriptor() ([]byte, []int) {
	return fileDescriptor_f03406d9d0fdefdf, []int{1}
}

func (m *GoMod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoMod.Unmarshal(m, b)
}
func (m *GoMod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoMod.Marshal(b, m, deterministic)
}
func (m *GoMod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoMod.Merge(m, src)
}
func (m *GoMod) XXX_Size() int {
	return xxx_messageInfo_GoMod.Size(m)
}
func (m *GoMod) XXX_DiscardUnknown() {
	xxx_messageInfo_GoMod.DiscardUnknown(m)
}

var xxx_messageInfo_GoMod proto.InternalMessageInfo

func (m *GoMod) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

var E_Module = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*Module)(nil),
	Field:         50000,
	Name:          "wxio.extensions.module.module",
	Tag:           "bytes,50000,opt,name=module",
	Filename:      "module_def.proto",
}

func init() {
	proto.RegisterType((*Module)(nil), "wxio.extensions.module.Module")
	proto.RegisterType((*GoMod)(nil), "wxio.extensions.module.GoMod")
	proto.RegisterExtension(E_Module)
}

func init() { proto.RegisterFile("module_def.proto", fileDescriptor_f03406d9d0fdefdf) }

var fileDescriptor_f03406d9d0fdefdf = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xcd, 0x4f, 0x29,
	0xcd, 0x49, 0x8d, 0x4f, 0x49, 0x4d, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2b, 0xaf,
	0xc8, 0xcc, 0xd7, 0x4b, 0xad, 0x28, 0x49, 0xcd, 0x2b, 0xce, 0xcc, 0xcf, 0x2b, 0xd6, 0x83, 0xa8,
	0x90, 0x52, 0x48, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xab, 0x4a, 0x2a, 0x4d, 0xd3, 0x4f,
	0x49, 0x2d, 0x4e, 0x2e, 0xca, 0x2c, 0x28, 0xc9, 0x2f, 0x82, 0xe8, 0x54, 0xb2, 0xe5, 0x62, 0xf3,
	0x05, 0xab, 0x15, 0x32, 0xe6, 0x62, 0x4d, 0xcf, 0xcf, 0xcd, 0x4f, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x36, 0x92, 0xd5, 0xc3, 0x6e, 0xa6, 0x9e, 0x7b, 0xbe, 0x6f, 0x7e, 0x4a, 0x10, 0x44, 0xad,
	0x92, 0x3c, 0x17, 0x2b, 0x98, 0x2f, 0x24, 0xc6, 0xc5, 0x06, 0x91, 0x07, 0x6b, 0xe7, 0x0c, 0x82,
	0xf2, 0xac, 0xc2, 0x60, 0xe2, 0x42, 0x32, 0x7a, 0x10, 0xc7, 0xe8, 0xc1, 0x1c, 0xa3, 0xe7, 0x96,
	0x99, 0x93, 0xea, 0x5f, 0x50, 0x02, 0x32, 0x5c, 0xe2, 0x42, 0x1b, 0x33, 0xd8, 0x5a, 0x39, 0x5c,
	0xd6, 0x42, 0x5c, 0x09, 0x33, 0xd7, 0x49, 0x27, 0x4a, 0x2b, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49,
	0x2f, 0x39, 0x3f, 0x57, 0x1f, 0xa4, 0x47, 0x3f, 0x3d, 0x3f, 0x25, 0x2f, 0x51, 0xbf, 0x20, 0x49,
	0x1f, 0xa1, 0x59, 0x1f, 0xa2, 0x3a, 0x89, 0x0d, 0x6c, 0xa7, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x16, 0x02, 0xfe, 0xff, 0x3a, 0x01, 0x00, 0x00,
}
